In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression # Logistic regression algorithm
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score # metric
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [2]:
data = pd.read_csv("train.csv")

In [3]:
data.head()

,age,workclass,final_weight,education,Learning years,marital-status,occupation,relationship,sex,capital-gain,capital-loss,Workrate,native-country,label,Id
0,31,Private,87891,Assoc-acdm,12,Married-civ-spouse,Sales,Husband,Male,0,0,60,United-States,1,1
1,32,State-gov,175931,HS-grad,9,Married-civ-spouse,Protective-serv,Husband,Male,0,0,40,United-States,1,2
2,41,Private,131591,HS-grad,9,Married-civ-spouse,Adm-clerical,Husband,Male,0,0,45,United-States,1,3
3,26,Private,160445,HS-grad,9,Divorced,Craft-repair,Not-in-family,Male,0,0,40,United-States,1,4
4,56,Private,179781,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,Male,0,0,40,United-States,0,5

In [4]:
data.tail()

,age,workclass,final_weight,education,Learning years,marital-status,occupation,relationship,sex,capital-gain,capital-loss,Workrate,native-country,label,Id
32556,30,Private,117393,HS-grad,9,Never-married,Sales,Not-in-family,Female,0,0,40,United-States,1,32557
32557,57,Self-emp-not-inc,95280,Some-college,10,Married-civ-spouse,Sales,Husband,Male,99999,0,45,United-States,0,32558
32558,56,Private,202220,Some-college,10,Separated,Tech-support,Unmarried,Female,0,0,38,United-States,1,32559
32559,56,Self-emp-inc,119891,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Male,0,1672,40,United-States,1,32560
32560,29,Self-emp-inc,138597,Assoc-acdm,12,Never-married,Prof-specialty,Other-relative,Female,0,0,40,United-States,1,32561

In [5]:
data.shape

(32561, 15)

In [6]:
data.drop(["Id"],axis=1,inplace=True)

In [7]:
data.describe()

,age,final_weight,Learning years,capital-gain,capital-loss,Workrate,label
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456,0.759190
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429,0.427581
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000,0.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000,1.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000,1.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000,1.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000,1.000000

In [8]:
data["label"].value_counts()

1    24720
0     7841
Name: label, dtype: int64

In [9]:
data.dtypes

age                int64
workclass         object
final_weight       int64
education         object
Learning years     int64
marital-status    object
occupation        object
relationship      object
sex               object
capital-gain       int64
capital-loss       int64
Workrate           int64
native-country    object
label              int64
dtype: object

In [10]:
data.isnull().any()

age               False
workclass          True
final_weight      False
education         False
Learning years    False
marital-status    False
occupation         True
relationship      False
sex               False
capital-gain      False
capital-loss      False
Workrate          False
native-country     True
label             False
dtype: bool

In [11]:
from sklearn.preprocessing import LabelEncoder,MinMaxScaler,OneHotEncoder
labelencoder = LabelEncoder()
# data['workclass']=data['workclass'].astype('category')
data['workclass'] = labelencoder.fit_transform(data['workclass'].astype(str))
data['education'] = labelencoder.fit_transform(data['education'])
# data['marital-status'] = labelencoder.fit_transform(data['marital-status'])
# data['occupation']=data['occupation'].astype('category')
data['occupation'] = labelencoder.fit_transform(data['occupation'].astype(str))
# data['relationship'] = labelencoder.fit_transform(data['relationship'])
# data['sex'] = labelencoder.fit_transform(data['sex'])
data['native-country'] = labelencoder.fit_transform(data['native-country'].astype(str))
data.head()

,age,workclass,final_weight,education,Learning years,marital-status,occupation,relationship,sex,capital-gain,capital-loss,Workrate,native-country,label
0,31,3,87891,7,12,Married-civ-spouse,11,Husband,Male,0,0,60,38,1
1,32,6,175931,11,9,Married-civ-spouse,10,Husband,Male,0,0,40,38,1
2,41,3,131591,11,9,Married-civ-spouse,0,Husband,Male,0,0,45,38,1
3,26,3,160445,11,9,Divorced,2,Not-in-family,Male,0,0,40,38,1
4,56,3,179781,11,9,Married-civ-spouse,3,Husband,Male,0,0,40,38,0

In [12]:
data.dropna()

,age,workclass,final_weight,education,Learning years,marital-status,occupation,relationship,sex,capital-gain,capital-loss,Workrate,native-country,label
0,31,3,87891,7,12,Married-civ-spouse,11,Husband,Male,0,0,60,38,1
1,32,6,175931,11,9,Married-civ-spouse,10,Husband,Male,0,0,40,38,1
2,41,3,131591,11,9,Married-civ-spouse,0,Husband,Male,0,0,45,38,1
3,26,3,160445,11,9,Divorced,2,Not-in-family,Male,0,0,40,38,1
4,56,3,179781,11,9,Married-civ-spouse,3,Husband,Male,0,0,40,38,0
5,32,3,309513,7,12,Married-civ-spouse,2,Husband,Male,0,0,40,38,1
6,20,3,221955,4,3,Married-spouse-absent,4,Other-relative,Male,0,0,40,25,1
7,38,3,127601,15,10,Widowed,3,Not-in-family,Female,0,0,40,38,0
8,52,3,225317,4,3,Married-civ-spouse,2,Husband,Male,0,0,40,25,1
9,31,1,158092,15,10,Never-married,0,Own-child,Female,0,0,35,38,1
10,52,3,109413,11,9,Never-married,11,Not-in-family,Male,0,0,40,38,1
11,22,3,218343,11,9,Never-married,7,Own-child,Female,0,0,40,38,1
12,31,3,226756,11,9,Never-married,0,Own-child,Male,0,0,40,38,1
13,23,3,126346,6,5,Never-married,7,Unmarried,Female,0,0,30,38,1
14,34,3,168768,7,12,Never-married,0,Not-in-family,Female,0,0,35,38,1
15,34,3,203488,15,10,Married-civ-spouse,13,Husband,Male,0,0,40,38,1
16,25,3,231638,11,9,Never-married,0,Own-child,Female,0,0,40,38,1
17,22,3,356567,8,11,Divorced,12,Not-in-family,Male,0,0,60,38,1
18,47,3,102771,11,9,Married-civ-spouse,13,Husband,Male,0,0,50,38,1
19,34,3,73161,11,9,Married-civ-spouse,11,Husband,Male,0,0,40,38,0
20,42,3,115085,11,9,Married-civ-spouse,0,Husband,Male,0,0,50,38,1
21,31,5,281030,11,9,Married-civ-spouse,2,Husband,Male,0,0,45,38,1
22,44,3,76196,9,13,Married-civ-spouse,3,Husband,Male,0,0,50,38,1
23,60,5,187794,11,9,Married-civ-spouse,13,Husband,Male,3103,0,60,38,0
24,23,3,204653,11,9,Never-married,5,Not-in-family,Male,0,0,72,5,1
25,32,5,34572,11,9,Divorced,4,Not-in-family,Male,0,0,65,38,1
26,51,3,221672,12,14,Married-civ-spouse,11,Husband,Male,15024,0,50,38,0
27,47,3,194772,8,11,Married-civ-spouse,6,Husband,Male,0,0,40,38,0
28,38,3,478346,11,9,Married-civ-spouse,3,Wife,Female,7688,0,40,38,0
29,42,3,180032,12,14,Never-married,9,Not-in-family,Female,0,0,40,38,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32531,40,3,132222,15,10,Married-civ-spouse,6,Husband,Male,4386,0,50,38,0
32532,36,3,278576,11,9,Married-civ-spouse,13,Husband,Male,0,0,50,38,1
32533,43,6,27661,12,14,Never-married,9,Not-in-family,Male,0,0,45,38,1
32534,59,3,35411,11,9,Widowed,6,Not-in-family,Female,0,0,40,38,1
32535,56,5,67841,11,9,Married-civ-spouse,11,Husband,Male,0,0,40,38,1
32536,31,3,309974,15,10,Separated,12,Unmarried,Female,0,0,40,38,1
32537,44,3,171424,9,13,Married-civ-spouse,9,Husband,Male,0,0,40,38,0
32538,23,3,233626,9,13,Never-married,11,Not-in-family,Male,0,0,25,38,1
32539,27,3,384308,15,10,Never-married,2,Not-in-family,Male,0,0,45,38,1
32540,35,3,77820,15,10,Married-civ-spouse,2,Husband,Male,0,0,60,38,1
32541,31,4,83748,15,10,Married-civ-spouse,3,Wife,Female,0,0,70,34,1
32542,31,0,294870,7,12,Married-civ-spouse,2,Husband,Male,0,0,40,38,1
32543,50,3,188186,12,14,Divorced,11,Not-in-family,Female,0,1590,45,38,1
32544,68,3,186350,11,9,Widowed,3,Not-in-family,Female,0,0,10,38,0
32545,22,3,124940,15,10,Married-civ-spouse,0,Wife,Female,0,0,44,38,1
32546,29,1,302422,8,11,Never-married,10,Not-in-family,Male,0,1564,56,38,0
32547,43,3,185057,11,9,Divorced,3,Not-in-family,Female,0,0,30,38,0
32548,37,3,89559,11,9,Divorced,0,Unmarried,Female,0,0,40,38,1
32549,22,3,51362,9,13,Never-married,11,Not-in-family,Female,0,0,16,38,1
32550,44,3,186916,12,14,Married-civ-spouse,3,Husband,Male,0,0,50,38,0
32551,20,3,211968,15,10,Never-married,9,Own-child,Female,0,0,15,38,1
32552,24,3,179203,2,8,Never-married,11,Other-relative,Male,0,0,55,38,1
32553,68,8,484298,1,7,Married-civ-spouse,14,Husband,Male,0,0,30,38,1
32554,23,3,241185,11,9,Never-married,0,Not-in-family,Female,0,0,40,38,1
32555,64,3,21174,11,9,Married-civ-spouse,3,Husband,Male,0,0,40,38,0
32556,30,3,117393,11,9,Never-married,11,Not-in-family,Female,0,0,40,38,1
32557,57,5,95280,15,10,Married-civ-spouse,11,Husband,Male,99999,0,45,38,0
32558,56,3,202220,15,10,Separated,12,Unmarried,Female,0,0,38,38,1
32559,56,4,119891,15,10,Married-civ-spouse,3,Husband,Male,0,1672,40,38,1
32560,29,4,138597,7,12,Never-married,9,Other-relative,Female,0,0,40,38,1

In [13]:
data.isnull().any()

age               False
workclass         False
final_weight      False
education         False
Learning years    False
marital-status    False
occupation        False
relationship      False
sex               False
capital-gain      False
capital-loss      False
Workrate          False
native-country    False
label             False
dtype: bool

In [14]:
# for index, row in data.iterrows():
# #     data.at[index,'net']=data.loc[index,'capital-gain']+data.loc[index,'capital-loss']
#     if(row['age']==90):
#         data.drop(index,inplace=True)
    
#     if(row['final_weight']>=1200000):
#         data.drop(index,inplace=True)
#     if(row['capital-gain']>=40000):
#         data.drop(index,inplace=True) 
#     if(row['capital-loss']>=30000):
#         data.drop(index,inplace=True)

In [15]:
# cleanup_nums = {"native-country":{"United-States": 1}}

In [16]:
# data.replace(cleanup_nums, inplace=True)
# data.head()

In [17]:
cleanup_nums = {"sex":{"Female": 0,"Male": 1}}

In [18]:
data.replace(cleanup_nums, inplace=True)
# data.head()

In [19]:
# cleanup_nums = {"native-country":{"Mexico": 0,"South": 2,"Dominican-Republic":39,"Philippines":3,"Taiwan":4,"Poland":5,"Cambodia":6,"Italy":7
#                                  ,"Cuba":8,"Jamaica":9,"Vietnam":10,"Canada":11,"El-Salvador":11,"Iran":12,"China":13,"Hong":14,"Haiti":15
#                                  ,"India":16,"Trinadad&Tobago":17,"Japan":18,"England":19,"Columbia":20,"Thailand":21,"Ireland":22
#                                  ,"Germany":23,"France":24,"Guatemala":25,"Honduras":26,"Greece":27,"Nicaragua":28,
#                                  "Puerto-Rico":29,"Peru":30,"Portugal":31,"Yugoslavia":32,"Hungary":33,"Laos":34,"Ecuador":35
#                                  ,"Scotland":36,"Outlying-US(Guam-USVI-etc)":37,"Holand-Netherlands":38}}

In [20]:
# data.replace(cleanup_nums, inplace=True)

In [21]:
cleanup_nums = {"relationship":{"Husband": 1,"Other-relative": 0,"Wife":1,"Not-in-family":0,"Own-child":0,"Unmarried":0}}

In [22]:
data.replace(cleanup_nums, inplace=True)

In [23]:
# data.head()

In [24]:
cleanup_nums = {"marital-status":{"Married-civ-spouse": 1,"Divorced": 0,"Never-married":0,"Separated":0,
                                  "Widowed":0,"Married-spouse-absent":0,"Married-AF-spouse":1}}

In [25]:
data.replace(cleanup_nums, inplace=True)

In [26]:
# cleanup_nums = {"workclass":{"Private": 1,"State-gov": 0,"Local-gov":2,"Federal-gov":3,"Self-emp-not-inc":4,
#                              "Self-emp-inc":5,"Without-pay":6,"Never-worked":7}}

In [27]:
# data.replace(cleanup_nums, inplace=True)

In [28]:
# cleanup_nums = {"occupation":{"Tech-support":0,
# "Transport-moving":1,
# "Sales":2,
# "Adm-clerical":3,
# "Craft-repair":4,
# "Exec-managerial":5,
# "Handlers-cleaners":6,
# "Farming-fishing":7,
# "Sales":8,
# "Machine-op-inspct":9,
# "Prof-specialty":10,
# "Other-service":11,"Protective-serv":12,"Armed-Forces":13,"Priv-house-serv":14
# }}

In [29]:
# data.replace(cleanup_nums, inplace=True)

In [30]:
# cleanup_nums = {"education":{"Assoc-acdm":0,
# "HS-grad":1,
# "5th-6th":2,
# "9th":3,
# "Bachelors":4,
# "Masters":5,
# "Assoc-voc":6,
# "11th":7,
# "Prof-school":8,
# "Preschool":9,
# "Prof-specialty":10,
# "10th":11,"7th-8th":12,"12th":13,"Some-college":14,"Doctorate":15,"1st-4th":16
# }}

In [31]:
data.to_csv("pre.csv")

In [32]:
data.drop(['marital-status'], axis=1, inplace=True)
# data.drop(['capital-gain'], axis=1, inplace=True)
# data.drop(['sex'], axis=1, inplace=True)
data.drop(['education'], axis=1, inplace=True)
# data.drop(['capital-loss'], axis=1, inplace=True)
# data.drop(['native-country'], axis=1, inplace=True)

In [33]:
# data.replace(cleanup_nums, inplace=True)
data.corr()

,age,workclass,final_weight,Learning years,occupation,relationship,sex,capital-gain,capital-loss,Workrate,native-country,label
age,1.000000,0.059423,-0.076646,0.036527,0.012626,0.321457,0.088832,0.077674,0.057775,0.068756,-0.000176,-0.234037
workclass,0.059423,1.000000,-0.019164,-0.054350,0.312511,0.001692,0.002306,0.010687,-0.009888,-0.093411,0.001253,0.055124
final_weight,-0.076646,-0.019164,1.000000,-0.043195,-0.000521,-0.028114,0.026858,0.000432,-0.010252,-0.018768,-0.062710,0.009463
Learning years,0.036527,-0.054350,-0.043195,1.000000,0.044096,0.092133,0.012280,0.122630,0.079923,0.148123,0.090277,-0.335154
occupation,0.012626,0.312511,-0.000521,0.044096,1.000000,-0.000095,0.026116,0.012350,0.004540,-0.056995,-0.000479,-0.010802
relationship,0.321457,0.001692,-0.028114,0.092133,-0.000095,1.000000,0.434780,0.086690,0.081816,0.214741,0.004863,-0.448496
sex,0.088832,0.002306,0.026858,0.012280,0.026116,0.434780,1.000000,0.048480,0.045567,0.229309,0.003013,-0.215980
capital-gain,0.077674,0.010687,0.000432,0.122630,0.012350,0.086690,0.048480,1.000000,-0.031615,0.078409,0.009651,-0.223329
capital-loss,0.057775,-0.009888,-0.010252,0.079923,0.004540,0.081816,0.045567,-0.031615,1.000000,0.054256,0.010037,-0.150526
Workrate,0.068756,-0.093411,-0.018768,0.148123,-0.056995,0.214741,0.229309,0.078409,0.054256,1.000000,0.007332,-0.229689
native-country,-0.000176,0.001253,-0.062710,0.090277,-0.000479,0.004863,0.003013,0.009651,0.010037,0.007332,1.000000,-0.023154
label,-0.234037,0.055124,0.009463,-0.335154,-0.010802,-0.448496,-0.215980,-0.223329,-0.150526,-0.229689,-0.023154,1.000000

In [34]:
data.describe()

,age,workclass,final_weight,Learning years,occupation,relationship,sex,capital-gain,capital-loss,Workrate,native-country,label
count,32561.000000,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,3.376371,1.897784e+05,10.080679,6.421762,0.453334,0.669205,1077.648844,87.303830,40.437456,36.470870,0.759190
std,13.640433,1.582038,1.055500e+05,2.572720,4.328619,0.497825,0.470506,7385.292085,402.960219,12.347429,6.083092,0.427581
min,17.000000,0.000000,1.228500e+04,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,28.000000,3.000000,1.178270e+05,9.000000,3.000000,0.000000,0.000000,0.000000,0.000000,40.000000,38.000000,1.000000
50%,37.000000,3.000000,1.783560e+05,10.000000,6.000000,0.000000,1.000000,0.000000,0.000000,40.000000,38.000000,1.000000
75%,48.000000,3.000000,2.370510e+05,12.000000,10.000000,1.000000,1.000000,0.000000,0.000000,45.000000,38.000000,1.000000
max,90.000000,8.000000,1.484705e+06,16.000000,14.000000,1.000000,1.000000,99999.000000,4356.000000,99.000000,41.000000,1.000000

In [35]:
# data["occupation"].fillna("6.499935", inplace = True) 
# data["native-country"].fillna("2.005410", inplace = True) 
# data["workclass"].fillna("1.485403", inplace = True)

In [36]:
data.isnull().any()

age               False
workclass         False
final_weight      False
Learning years    False
occupation        False
relationship      False
sex               False
capital-gain      False
capital-loss      False
Workrate          False
native-country    False
label             False
dtype: bool

In [37]:
data["label"] = data["label"].map({1:0,0:1})
# data = data.drop(["age"],axis=1)

data.head()

,age,workclass,final_weight,Learning years,occupation,relationship,sex,capital-gain,capital-loss,Workrate,native-country,label
0,31,3,87891,12,11,1,1,0,0,60,38,0
1,32,6,175931,9,10,1,1,0,0,40,38,0
2,41,3,131591,9,0,1,1,0,0,45,38,0
3,26,3,160445,9,2,0,1,0,0,40,38,0
4,56,3,179781,9,3,1,1,0,0,40,38,1

In [38]:
y = data["label"]

X = data.drop(["label"],axis=1)

X.shape

(32561, 11)

In [39]:
x_train , x_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [40]:
lr = LogisticRegression(C=1.3,max_iter=100)

In [41]:
scaler=StandardScaler()
X_train = scaler.fit_transform(x_train)
X_test = scaler.transform(x_test)

In [42]:
lr.fit(X_train,y_train)

LogisticRegression(C=1.3, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [43]:
prediction_train = lr.predict(X_train)
print(accuracy_score(y_true=y_train,y_pred=prediction_train))

0.8429437960687961

In [44]:
prediction_test = lr.predict(X_test)
print(accuracy_score(y_true=y_test,y_pred=prediction_test))

0.8446184553968985

In [45]:
scaler=StandardScaler()
X_train = scaler.fit_transform(x_train)
X_test = scaler.transform(x_test)

In [46]:
from sklearn.svm import SVC
clf = SVC(gamma='auto',C=3.5,cache_size=1000,kernel='rbf')
clf.fit(X_train, y_train)

SVC(C=3.5, cache_size=1000, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [47]:
prediction_train1 = clf.predict(X_train)
print(accuracy_score(y_true=y_train,y_pred=prediction_train1))
prediction_test1 = clf.predict(X_test)
y_true=y_test
y_pred=prediction_test1
print(accuracy_score(y_true=y_test,y_pred=prediction_test1))

0.859720515970516
0.852141870105942

In [48]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_true, y_pred)

array([[4676,  265],
       [ 698,  874]])

In [49]:
# from sklearn.neighbors import KNeighborsClassifier

# knn = KNeighborsClassifier(n_neighbors=31)
# # fit the model with data
# knn.fit(X_train, y_train)
# k_pred = knn.predict(X_train)
# print(accuracy_score(y_true=y_train,y_pred=k_pred))
# prediction_test1 = knn.predict(X_test)
# print(accuracy_score(y_true=y_test,y_pred=prediction_test1))

In [50]:
scaler=StandardScaler()
X_train = scaler.fit_transform(x_train)
X_test = scaler.transform(x_test)

In [51]:
# from sklearn.ensemble import RandomForestClassifier
# rf = RandomForestClassifier()
# rf.fit(X_train, y_train)

In [52]:
# prediction_train1 = rf.predict(X_train)
# print(accuracy_score(y_true=y_train,y_pred=prediction_train1))
# prediction_test1 = rf.predict(X_test)
# y_true=y_test
# y_pred=prediction_test1
# print(accuracy_score(y_true=y_test,y_pred=prediction_test1))

In [53]:
from sklearn.ensemble import GradientBoostingClassifier
gf = GradientBoostingClassifier()
gf.fit(X_train, y_train) 
prediction_train1 = gf.predict(X_train)
print(accuracy_score(y_true=y_train,y_pred=prediction_train1))
prediction_test1 = gf.predict(X_test)
y_true=y_test
y_pred=prediction_test1
print(accuracy_score(y_true=y_test,y_pred=prediction_test1))

/home/redhat/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

0.8685119778869779
0.8667280822969445

In [54]:
from catboost import CatBoostClassifier
# from xgboost import XGBClassifier

# cxg= XGBClassifier()
ct= CatBoostClassifier()
ct.fit(X_train, y_train) 
prediction_train1 = ct.predict(X_train)
print(accuracy_score(y_true=y_train,y_pred=prediction_train1))
prediction_test1 = ct.predict(X_test)
y_true=y_test
y_pred=prediction_test1
print(accuracy_score(y_true=y_test,y_pred=prediction_test1))

Learning rate set to 0.042149
0:	learn: 0.6504202	total: 95.7ms	remaining: 1m 35s
1:	learn: 0.6128022	total: 118ms	remaining: 59.1s
2:	learn: 0.5821701	total: 169ms	remaining: 56.3s
3:	learn: 0.5537279	total: 202ms	remaining: 50.2s
4:	learn: 0.5261640	total: 262ms	remaining: 52.1s
5:	learn: 0.5058241	total: 288ms	remaining: 47.7s
6:	learn: 0.4839989	total: 353ms	remaining: 50s
7:	learn: 0.4659145	total: 406ms	remaining: 50.3s
8:	learn: 0.4513523	total: 446ms	remaining: 49.1s
9:	learn: 0.4380277	total: 499ms	remaining: 49.4s
10:	learn: 0.4253922	total: 527ms	remaining: 47.4s
11:	learn: 0.4160626	total: 584ms	remaining: 48.1s
12:	learn: 0.4068309	total: 613ms	remaining: 46.5s
13:	learn: 0.3975121	total: 679ms	remaining: 47.8s
14:	learn: 0.3896908	total: 704ms	remaining: 46.3s
15:	learn: 0.3829002	total: 761ms	remaining: 46.8s
16:	learn: 0.3771617	total: 787ms	remaining: 45.5s
17:	learn: 0.3709656	total: 860ms	remaining: 46.9s
18:	learn: 0.3663854	total: 916ms	remaining: 47.3s
19:	learn: 0.3623652	total: 947ms	remaining: 46.4s
20:	learn: 0.3587373	total: 1.01s	remaining: 47.2s
21:	learn: 0.3542260	total: 1.04s	remaining: 46.5s
22:	learn: 0.3506771	total: 1.08s	remaining: 45.9s
23:	learn: 0.3479245	total: 1.14s	remaining: 46.3s
24:	learn: 0.3450475	total: 1.16s	remaining: 45.3s
25:	learn: 0.3425104	total: 1.22s	remaining: 45.7s
26:	learn: 0.3400724	total: 1.28s	remaining: 46s
27:	learn: 0.3379270	total: 1.32s	remaining: 45.8s
28:	learn: 0.3360848	total: 1.38s	remaining: 46.2s
29:	learn: 0.3342436	total: 1.4s	remaining: 45.4s
30:	learn: 0.3323360	total: 1.48s	remaining: 46.2s
31:	learn: 0.3306441	total: 1.54s	remaining: 46.7s
32:	learn: 0.3297398	total: 1.58s	remaining: 46.3s
33:	learn: 0.3279081	total: 1.64s	remaining: 46.5s
34:	learn: 0.3266351	total: 1.66s	remaining: 45.9s
35:	learn: 0.3259031	total: 1.73s	remaining: 46.2s
36:	learn: 0.3249582	total: 1.76s	remaining: 45.8s
37:	learn: 0.3236399	total: 1.82s	remaining: 46.2s
38:	learn: 0.3226632	total: 1.85s	remaining: 45.7s
39:	learn: 0.3218352	total: 1.91s	remaining: 45.9s
40:	learn: 0.3214199	total: 1.94s	remaining: 45.3s
41:	learn: 0.3203350	total: 2.01s	remaining: 45.8s
42:	learn: 0.3193674	total: 2.04s	remaining: 45.4s
43:	learn: 0.3182739	total: 2.1s	remaining: 45.5s
44:	learn: 0.3174648	total: 2.12s	remaining: 45s
45:	learn: 0.3166734	total: 2.18s	remaining: 45.3s
46:	learn: 0.3158375	total: 2.21s	remaining: 44.9s
47:	learn: 0.3153047	total: 2.28s	remaining: 45.2s
48:	learn: 0.3149970	total: 2.3s	remaining: 44.7s
49:	learn: 0.3142836	total: 2.36s	remaining: 44.8s
50:	learn: 0.3138055	total: 2.38s	remaining: 44.3s
51:	learn: 0.3133627	total: 2.44s	remaining: 44.5s
52:	learn: 0.3128649	total: 2.47s	remaining: 44.1s
53:	learn: 0.3120840	total: 2.53s	remaining: 44.3s
54:	learn: 0.3112266	total: 2.55s	remaining: 43.9s
55:	learn: 0.3103950	total: 2.62s	remaining: 44.1s
56:	learn: 0.3101519	total: 2.64s	remaining: 43.7s
57:	learn: 0.3098090	total: 2.7s	remaining: 43.9s
58:	learn: 0.3093910	total: 2.73s	remaining: 43.5s
59:	learn: 0.3085816	total: 2.79s	remaining: 43.7s
60:	learn: 0.3082108	total: 2.81s	remaining: 43.3s
61:	learn: 0.3079449	total: 2.87s	remaining: 43.4s
62:	learn: 0.3075235	total: 2.9s	remaining: 43.1s
63:	learn: 0.3070571	total: 2.96s	remaining: 43.3s
64:	learn: 0.3067021	total: 2.99s	remaining: 43s
65:	learn: 0.3064435	total: 3.05s	remaining: 43.1s
66:	learn: 0.3058870	total: 3.07s	remaining: 42.8s
67:	learn: 0.3056827	total: 3.13s	remaining: 42.9s
68:	learn: 0.3052590	total: 3.15s	remaining: 42.6s
69:	learn: 0.3048158	total: 3.22s	remaining: 42.8s
70:	learn: 0.3042496	total: 3.24s	remaining: 42.4s
71:	learn: 0.3038820	total: 3.3s	remaining: 42.5s
72:	learn: 0.3033451	total: 3.32s	remaining: 42.2s
73:	learn: 0.3030183	total: 3.38s	remaining: 42.3s
74:	learn: 0.3025932	total: 3.4s	remaining: 42s
75:	learn: 0.3022182	total: 3.46s	remaining: 42s
76:	learn: 0.3017357	total: 3.49s	remaining: 41.9s
77:	learn: 0.3013584	total: 3.55s	remaining: 42s
78:	learn: 0.3011003	total: 3.57s	remaining: 41.7s
79:	learn: 0.3008821	total: 3.6s	remaining: 41.4s
80:	learn: 0.3004864	total: 3.65s	remaining: 41.5s
81:	learn: 0.3003420	total: 3.69s	remaining: 41.3s
82:	learn: 0.2997471	total: 3.74s	remaining: 41.3s
83:	learn: 0.2995116	total: 3.77s	remaining: 41.2s
84:	learn: 0.2992761	total: 3.83s	remaining: 41.2s
85:	learn: 0.2990926	total: 3.86s	remaining: 41s
86:	learn: 0.2987325	total: 3.88s	remaining: 40.8s
87:	learn: 0.2982686	total: 3.95s	remaining: 41s
88:	learn: 0.2980684	total: 4s	remaining: 40.9s
89:	learn: 0.2978209	total: 4.04s	remaining: 40.8s
90:	learn: 0.2974538	total: 4.06s	remaining: 40.5s
91:	learn: 0.2971052	total: 4.12s	remaining: 40.6s
92:	learn: 0.2968099	total: 4.14s	remaining: 40.4s
93:	learn: 0.2965967	total: 4.2s	remaining: 40.5s
94:	learn: 0.2962705	total: 4.23s	remaining: 40.3s
95:	learn: 0.2960909	total: 4.28s	remaining: 40.3s
96:	learn: 0.2956719	total: 4.31s	remaining: 40.1s
97:	learn: 0.2954903	total: 4.36s	remaining: 40.2s
98:	learn: 0.2953198	total: 4.39s	remaining: 39.9s
99:	learn: 0.2950682	total: 4.45s	remaining: 40.1s
100:	learn: 0.2948438	total: 4.48s	remaining: 39.9s
101:	learn: 0.2944916	total: 4.53s	remaining: 39.9s
102:	learn: 0.2942884	total: 4.55s	remaining: 39.6s
103:	learn: 0.2941544	total: 4.61s	remaining: 39.7s
104:	learn: 0.2939405	total: 4.63s	remaining: 39.5s
105:	learn: 0.2936116	total: 4.7s	remaining: 39.6s
106:	learn: 0.2932928	total: 4.73s	remaining: 39.5s
107:	learn: 0.2931203	total: 4.79s	remaining: 39.5s
108:	learn: 0.2929965	total: 4.82s	remaining: 39.4s
109:	learn: 0.2927799	total: 4.88s	remaining: 39.4s
110:	learn: 0.2924912	total: 4.91s	remaining: 39.3s
111:	learn: 0.2922382	total: 4.97s	remaining: 39.4s
112:	learn: 0.2917954	total: 4.99s	remaining: 39.2s
113:	learn: 0.2916433	total: 5.05s	remaining: 39.2s
114:	learn: 0.2911970	total: 5.07s	remaining: 39s
115:	learn: 0.2910927	total: 5.13s	remaining: 39.1s
116:	learn: 0.2909359	total: 5.16s	remaining: 38.9s
117:	learn: 0.2908242	total: 5.21s	remaining: 39s
118:	learn: 0.2906772	total: 5.24s	remaining: 38.8s
119:	learn: 0.2905286	total: 5.29s	remaining: 38.8s
120:	learn: 0.2904324	total: 5.32s	remaining: 38.7s
121:	learn: 0.2902756	total: 5.38s	remaining: 38.7s
122:	learn: 0.2901404	total: 5.41s	remaining: 38.6s
123:	learn: 0.2900263	total: 5.46s	remaining: 38.6s
124:	learn: 0.2898721	total: 5.49s	remaining: 38.4s
125:	learn: 0.2896631	total: 5.51s	remaining: 38.2s
126:	learn: 0.2894683	total: 5.56s	remaining: 38.3s
127:	learn: 0.2893645	total: 5.59s	remaining: 38.1s
128:	learn: 0.2892878	total: 5.65s	remaining: 38.1s
129:	learn: 0.2891939	total: 5.67s	remaining: 38s
130:	learn: 0.2889378	total: 5.73s	remaining: 38s
131:	learn: 0.2888741	total: 5.75s	remaining: 37.8s
132:	learn: 0.2887761	total: 5.81s	remaining: 37.9s
133:	learn: 0.2886893	total: 5.84s	remaining: 37.7s
134:	learn: 0.2886060	total: 5.9s	remaining: 37.8s
135:	learn: 0.2885370	total: 5.92s	remaining: 37.6s
136:	learn: 0.2884537	total: 5.94s	remaining: 37.4s
137:	learn: 0.2883742	total: 6s	remaining: 37.5s
138:	learn: 0.2883181	total: 6.03s	remaining: 37.4s
139:	learn: 0.2882007	total: 6.09s	remaining: 37.4s
140:	learn: 0.2880960	total: 6.12s	remaining: 37.3s
141:	learn: 0.2880353	total: 6.17s	remaining: 37.3s
142:	learn: 0.2879398	total: 6.2s	remaining: 37.2s
143:	learn: 0.2878535	total: 6.26s	remaining: 37.2s
144:	learn: 0.2876836	total: 6.28s	remaining: 37.1s
145:	learn: 0.2875469	total: 6.34s	remaining: 37.1s
146:	learn: 0.2873611	total: 6.36s	remaining: 36.9s
147:	learn: 0.2872014	total: 6.42s	remaining: 36.9s
148:	learn: 0.2870597	total: 6.45s	remaining: 36.8s
149:	learn: 0.2869056	total: 6.5s	remaining: 36.9s
150:	learn: 0.2866470	total: 6.53s	remaining: 36.7s
151:	learn: 0.2864606	total: 6.59s	remaining: 36.8s
152:	learn: 0.2861572	total: 6.61s	remaining: 36.6s
153:	learn: 0.2860831	total: 6.67s	remaining: 36.6s
154:	learn: 0.2859907	total: 6.69s	remaining: 36.5s
155:	learn: 0.2859451	total: 6.76s	remaining: 36.6s
156:	learn: 0.2857884	total: 6.78s	remaining: 36.4s
157:	learn: 0.2857367	total: 6.84s	remaining: 36.4s
158:	learn: 0.2855779	total: 6.86s	remaining: 36.3s
159:	learn: 0.2855164	total: 6.92s	remaining: 36.3s
160:	learn: 0.2853995	total: 6.94s	remaining: 36.2s

161:	learn: 0.2853461	total: 7.01s	remaining: 36.2s
162:	learn: 0.2852484	total: 7.03s	remaining: 36.1s
163:	learn: 0.2852159	total: 7.09s	remaining: 36.1s
164:	learn: 0.2850242	total: 7.12s	remaining: 36s
165:	learn: 0.2849482	total: 7.17s	remaining: 36s
166:	learn: 0.2848337	total: 7.2s	remaining: 35.9s
167:	learn: 0.2847652	total: 7.25s	remaining: 35.9s
168:	learn: 0.2846842	total: 7.28s	remaining: 35.8s
169:	learn: 0.2846136	total: 7.3s	remaining: 35.7s
170:	learn: 0.2844970	total: 7.36s	remaining: 35.7s
171:	learn: 0.2843762	total: 7.38s	remaining: 35.5s
172:	learn: 0.2843559	total: 7.44s	remaining: 35.5s
173:	learn: 0.2842389	total: 7.46s	remaining: 35.4s
174:	learn: 0.2841693	total: 7.52s	remaining: 35.5s
175:	learn: 0.2840824	total: 7.54s	remaining: 35.3s
176:	learn: 0.2840085	total: 7.6s	remaining: 35.3s
177:	learn: 0.2839842	total: 7.63s	remaining: 35.2s
178:	learn: 0.2838230	total: 7.68s	remaining: 35.2s
179:	learn: 0.2837716	total: 7.71s	remaining: 35.1s
180:	learn: 0.2837122	total: 7.76s	remaining: 35.1s
181:	learn: 0.2836181	total: 7.79s	remaining: 35s
182:	learn: 0.2835413	total: 7.84s	remaining: 35s
183:	learn: 0.2834798	total: 7.87s	remaining: 34.9s
184:	learn: 0.2834446	total: 7.9s	remaining: 34.8s
185:	learn: 0.2833858	total: 7.95s	remaining: 34.8s
186:	learn: 0.2833346	total: 7.98s	remaining: 34.7s
187:	learn: 0.2831173	total: 8.03s	remaining: 34.7s
188:	learn: 0.2830512	total: 8.06s	remaining: 34.6s
189:	learn: 0.2829459	total: 8.12s	remaining: 34.6s
190:	learn: 0.2828634	total: 8.15s	remaining: 34.5s
191:	learn: 0.2824011	total: 8.17s	remaining: 34.4s
192:	learn: 0.2823427	total: 8.23s	remaining: 34.4s
193:	learn: 0.2823127	total: 8.25s	remaining: 34.3s
194:	learn: 0.2822157	total: 8.31s	remaining: 34.3s
195:	learn: 0.2821584	total: 8.34s	remaining: 34.2s
196:	learn: 0.2820923	total: 8.39s	remaining: 34.2s
197:	learn: 0.2820239	total: 8.42s	remaining: 34.1s
198:	learn: 0.2819781	total: 8.47s	remaining: 34.1s
199:	learn: 0.2818303	total: 8.5s	remaining: 34s
200:	learn: 0.2815217	total: 8.56s	remaining: 34s
201:	learn: 0.2814759	total: 8.58s	remaining: 33.9s
202:	learn: 0.2814409	total: 8.64s	remaining: 33.9s
203:	learn: 0.2813541	total: 8.66s	remaining: 33.8s
204:	learn: 0.2812531	total: 8.69s	remaining: 33.7s
205:	learn: 0.2812250	total: 8.74s	remaining: 33.7s
206:	learn: 0.2811477	total: 8.77s	remaining: 33.6s
207:	learn: 0.2808643	total: 8.82s	remaining: 33.6s
208:	learn: 0.2808187	total: 8.85s	remaining: 33.5s
209:	learn: 0.2807697	total: 8.91s	remaining: 33.5s
210:	learn: 0.2806995	total: 8.93s	remaining: 33.4s
211:	learn: 0.2806258	total: 8.99s	remaining: 33.4s
212:	learn: 0.2805519	total: 9.02s	remaining: 33.3s
213:	learn: 0.2804878	total: 9.08s	remaining: 33.3s
214:	learn: 0.2803779	total: 9.11s	remaining: 33.2s
215:	learn: 0.2803296	total: 9.16s	remaining: 33.2s
216:	learn: 0.2802796	total: 9.19s	remaining: 33.1s
217:	learn: 0.2802472	total: 9.25s	remaining: 33.2s
218:	learn: 0.2801289	total: 9.27s	remaining: 33.1s
219:	learn: 0.2800969	total: 9.32s	remaining: 33s
220:	learn: 0.2799181	total: 9.35s	remaining: 32.9s
221:	learn: 0.2798515	total: 9.4s	remaining: 32.9s
222:	learn: 0.2798018	total: 9.43s	remaining: 32.9s
223:	learn: 0.2797207	total: 9.49s	remaining: 32.9s
224:	learn: 0.2796725	total: 9.51s	remaining: 32.8s
225:	learn: 0.2795745	total: 9.57s	remaining: 32.8s
226:	learn: 0.2795605	total: 9.59s	remaining: 32.7s
227:	learn: 0.2794926	total: 9.65s	remaining: 32.7s
228:	learn: 0.2794437	total: 9.68s	remaining: 32.6s
229:	learn: 0.2792838	total: 9.74s	remaining: 32.6s
230:	learn: 0.2792032	total: 9.77s	remaining: 32.5s
231:	learn: 0.2791638	total: 9.82s	remaining: 32.5s
232:	learn: 0.2787694	total: 9.85s	remaining: 32.4s
233:	learn: 0.2787545	total: 9.91s	remaining: 32.4s
234:	learn: 0.2787343	total: 9.93s	remaining: 32.3s
235:	learn: 0.2787034	total: 10s	remaining: 32.4s
236:	learn: 0.2783935	total: 10.1s	remaining: 32.4s
237:	learn: 0.2783581	total: 10.1s	remaining: 32.3s
238:	learn: 0.2783238	total: 10.1s	remaining: 32.3s
239:	learn: 0.2782444	total: 10.2s	remaining: 32.2s
240:	learn: 0.2780571	total: 10.2s	remaining: 32.2s
241:	learn: 0.2780148	total: 10.3s	remaining: 32.2s
242:	learn: 0.2779910	total: 10.3s	remaining: 32.1s
243:	learn: 0.2779039	total: 10.4s	remaining: 32.1s
244:	learn: 0.2776110	total: 10.4s	remaining: 32s
245:	learn: 0.2775596	total: 10.4s	remaining: 32s
246:	learn: 0.2774917	total: 10.5s	remaining: 31.9s
247:	learn: 0.2774131	total: 10.5s	remaining: 31.9s
248:	learn: 0.2773919	total: 10.6s	remaining: 31.8s
249:	learn: 0.2772810	total: 10.6s	remaining: 31.8s
250:	learn: 0.2771957	total: 10.6s	remaining: 31.7s
251:	learn: 0.2770515	total: 10.7s	remaining: 31.7s
252:	learn: 0.2770115	total: 10.7s	remaining: 31.6s
253:	learn: 0.2768364	total: 10.8s	remaining: 31.7s
254:	learn: 0.2767735	total: 10.8s	remaining: 31.6s
255:	learn: 0.2767128	total: 10.9s	remaining: 31.6s
256:	learn: 0.2766352	total: 10.9s	remaining: 31.6s
257:	learn: 0.2764720	total: 11s	remaining: 31.5s
258:	learn: 0.2762767	total: 11s	remaining: 31.5s
259:	learn: 0.2762339	total: 11s	remaining: 31.4s
260:	learn: 0.2761870	total: 11.1s	remaining: 31.3s
261:	learn: 0.2761565	total: 11.1s	remaining: 31.2s
262:	learn: 0.2760726	total: 11.2s	remaining: 31.3s
263:	learn: 0.2759741	total: 11.2s	remaining: 31.2s
264:	learn: 0.2758934	total: 11.2s	remaining: 31.1s
265:	learn: 0.2758669	total: 11.3s	remaining: 31.1s
266:	learn: 0.2758052	total: 11.3s	remaining: 31s
267:	learn: 0.2757604	total: 11.3s	remaining: 31s
268:	learn: 0.2755592	total: 11.4s	remaining: 30.9s
269:	learn: 0.2755220	total: 11.4s	remaining: 30.9s
270:	learn: 0.2754413	total: 11.5s	remaining: 30.8s
271:	learn: 0.2754133	total: 11.5s	remaining: 30.8s
272:	learn: 0.2753622	total: 11.5s	remaining: 30.8s
273:	learn: 0.2751701	total: 11.6s	remaining: 30.7s
274:	learn: 0.2751233	total: 11.6s	remaining: 30.7s
275:	learn: 0.2750584	total: 11.7s	remaining: 30.6s
276:	learn: 0.2750416	total: 11.7s	remaining: 30.6s
277:	learn: 0.2750212	total: 11.7s	remaining: 30.5s
278:	learn: 0.2749781	total: 11.8s	remaining: 30.5s
279:	learn: 0.2748455	total: 11.8s	remaining: 30.4s
280:	learn: 0.2748001	total: 11.9s	remaining: 30.5s
281:	learn: 0.2747878	total: 11.9s	remaining: 30.4s
282:	learn: 0.2747200	total: 12s	remaining: 30.4s
283:	learn: 0.2747067	total: 12s	remaining: 30.3s
284:	learn: 0.2746887	total: 12.1s	remaining: 30.3s
285:	learn: 0.2746219	total: 12.1s	remaining: 30.2s
286:	learn: 0.2745192	total: 12.2s	remaining: 30.2s
287:	learn: 0.2744704	total: 12.2s	remaining: 30.2s
288:	learn: 0.2743949	total: 12.3s	remaining: 30.2s
289:	learn: 0.2743302	total: 12.3s	remaining: 30.2s
290:	learn: 0.2742625	total: 12.4s	remaining: 30.1s
291:	learn: 0.2742618	total: 12.4s	remaining: 30s
292:	learn: 0.2741932	total: 12.4s	remaining: 30s
293:	learn: 0.2741926	total: 12.5s	remaining: 29.9s
294:	learn: 0.2741117	total: 12.5s	remaining: 29.9s
295:	learn: 0.2740510	total: 12.6s	remaining: 29.9s
296:	learn: 0.2740199	total: 12.6s	remaining: 29.9s
297:	learn: 0.2740061	total: 12.7s	remaining: 29.8s
298:	learn: 0.2739878	total: 12.7s	remaining: 29.8s
299:	learn: 0.2739666	total: 12.8s	remaining: 29.8s
300:	learn: 0.2739088	total: 12.8s	remaining: 29.7s
301:	learn: 0.2739073	total: 12.8s	remaining: 29.6s
302:	learn: 0.2738376	total: 12.9s	remaining: 29.6s
303:	learn: 0.2738304	total: 12.9s	remaining: 29.6s
304:	learn: 0.2736989	total: 13s	remaining: 29.6s
305:	learn: 0.2736567	total: 13s	remaining: 29.6s
306:	learn: 0.2736409	total: 13.1s	remaining: 29.5s
307:	learn: 0.2736090	total: 13.1s	remaining: 29.5s
308:	learn: 0.2734554	total: 13.2s	remaining: 29.5s
309:	learn: 0.2733931	total: 13.2s	remaining: 29.4s
310:	learn: 0.2733149	total: 13.3s	remaining: 29.4s
311:	learn: 0.2733009	total: 13.3s	remaining: 29.3s
312:	learn: 0.2732408	total: 13.3s	remaining: 29.3s
313:	learn: 0.2731978	total: 13.4s	remaining: 29.2s
314:	learn: 0.2731794	total: 13.4s	remaining: 29.2s
315:	learn: 0.2731431	total: 13.5s	remaining: 29.2s
316:	learn: 0.2730227	total: 13.5s	remaining: 29.1s
317:	learn: 0.2729941	total: 13.6s	remaining: 29.1s
318:	learn: 0.2729211	total: 13.6s	remaining: 29s
319:	learn: 0.2728530	total: 13.7s	remaining: 29s
320:	learn: 0.2727448	total: 13.7s	remaining: 29s
321:	learn: 0.2727437	total: 13.7s	remaining: 28.9s
322:	learn: 0.2726989	total: 13.8s	remaining: 28.8s
323:	learn: 0.2726724	total: 13.8s	remaining: 28.8s
324:	learn: 0.2726162	total: 13.8s	remaining: 28.8s

325:	learn: 0.2726096	total: 13.9s	remaining: 28.7s
326:	learn: 0.2726093	total: 13.9s	remaining: 28.7s
327:	learn: 0.2725672	total: 14s	remaining: 28.6s
328:	learn: 0.2725166	total: 14s	remaining: 28.6s
329:	learn: 0.2724616	total: 14.1s	remaining: 28.6s
330:	learn: 0.2724616	total: 14.1s	remaining: 28.5s
331:	learn: 0.2724493	total: 14.1s	remaining: 28.4s
332:	learn: 0.2724485	total: 14.2s	remaining: 28.4s
333:	learn: 0.2723922	total: 14.2s	remaining: 28.3s
334:	learn: 0.2723805	total: 14.2s	remaining: 28.3s
335:	learn: 0.2723336	total: 14.3s	remaining: 28.3s
336:	learn: 0.2722940	total: 14.3s	remaining: 28.2s
337:	learn: 0.2722637	total: 14.4s	remaining: 28.2s
338:	learn: 0.2722559	total: 14.4s	remaining: 28.1s
339:	learn: 0.2722452	total: 14.5s	remaining: 28.1s
340:	learn: 0.2721485	total: 14.5s	remaining: 28s
341:	learn: 0.2721476	total: 14.5s	remaining: 27.9s
342:	learn: 0.2721108	total: 14.6s	remaining: 27.9s
343:	learn: 0.2721100	total: 14.6s	remaining: 27.8s
344:	learn: 0.2719816	total: 14.7s	remaining: 27.8s
345:	learn: 0.2719548	total: 14.7s	remaining: 27.7s
346:	learn: 0.2719204	total: 14.7s	remaining: 27.7s
347:	learn: 0.2719202	total: 14.8s	remaining: 27.6s
348:	learn: 0.2718607	total: 14.8s	remaining: 27.6s
349:	learn: 0.2718391	total: 14.8s	remaining: 27.6s
350:	learn: 0.2718247	total: 14.9s	remaining: 27.5s
351:	learn: 0.2717486	total: 14.9s	remaining: 27.5s
352:	learn: 0.2717482	total: 15s	remaining: 27.4s
353:	learn: 0.2717164	total: 15s	remaining: 27.4s
354:	learn: 0.2716877	total: 15.1s	remaining: 27.3s
355:	learn: 0.2716254	total: 15.1s	remaining: 27.3s
356:	learn: 0.2715867	total: 15.1s	remaining: 27.2s
357:	learn: 0.2715628	total: 15.2s	remaining: 27.2s
358:	learn: 0.2715040	total: 15.2s	remaining: 27.1s
359:	learn: 0.2714454	total: 15.2s	remaining: 27.1s
360:	learn: 0.2713565	total: 15.3s	remaining: 27s
361:	learn: 0.2713141	total: 15.3s	remaining: 27s
362:	learn: 0.2713042	total: 15.3s	remaining: 26.9s
363:	learn: 0.2712089	total: 15.4s	remaining: 26.9s
364:	learn: 0.2711623	total: 15.4s	remaining: 26.8s
365:	learn: 0.2711620	total: 15.4s	remaining: 26.7s
366:	learn: 0.2711398	total: 15.5s	remaining: 26.7s
367:	learn: 0.2711394	total: 15.5s	remaining: 26.6s
368:	learn: 0.2711084	total: 15.6s	remaining: 26.6s
369:	learn: 0.2710470	total: 15.6s	remaining: 26.6s
370:	learn: 0.2710026	total: 15.7s	remaining: 26.5s
371:	learn: 0.2709510	total: 15.7s	remaining: 26.5s
372:	learn: 0.2708997	total: 15.7s	remaining: 26.5s
373:	learn: 0.2708765	total: 15.8s	remaining: 26.4s
374:	learn: 0.2708148	total: 15.8s	remaining: 26.4s
375:	learn: 0.2708095	total: 15.9s	remaining: 26.3s
376:	learn: 0.2707876	total: 15.9s	remaining: 26.3s
377:	learn: 0.2707769	total: 16s	remaining: 26.3s
378:	learn: 0.2707094	total: 16s	remaining: 26.2s
379:	learn: 0.2706522	total: 16.1s	remaining: 26.2s
380:	learn: 0.2706174	total: 16.1s	remaining: 26.1s
381:	learn: 0.2706172	total: 16.1s	remaining: 26.1s
382:	learn: 0.2706026	total: 16.2s	remaining: 26.1s
383:	learn: 0.2706025	total: 16.2s	remaining: 26s
384:	learn: 0.2705802	total: 16.3s	remaining: 26s
385:	learn: 0.2705800	total: 16.3s	remaining: 25.9s
386:	learn: 0.2705800	total: 16.3s	remaining: 25.9s
387:	learn: 0.2705761	total: 16.4s	remaining: 25.8s
388:	learn: 0.2705475	total: 16.4s	remaining: 25.8s
389:	learn: 0.2704477	total: 16.5s	remaining: 25.8s
390:	learn: 0.2703283	total: 16.5s	remaining: 25.7s
391:	learn: 0.2703097	total: 16.6s	remaining: 25.7s
392:	learn: 0.2702938	total: 16.6s	remaining: 25.7s
393:	learn: 0.2702734	total: 16.7s	remaining: 25.6s
394:	learn: 0.2702144	total: 16.7s	remaining: 25.6s
395:	learn: 0.2701989	total: 16.7s	remaining: 25.5s
396:	learn: 0.2701363	total: 16.8s	remaining: 25.5s
397:	learn: 0.2701078	total: 16.8s	remaining: 25.4s
398:	learn: 0.2700814	total: 16.9s	remaining: 25.4s
399:	learn: 0.2699769	total: 16.9s	remaining: 25.3s
400:	learn: 0.2698932	total: 17s	remaining: 25.3s
401:	learn: 0.2698443	total: 17s	remaining: 25.3s
402:	learn: 0.2698068	total: 17s	remaining: 25.2s
403:	learn: 0.2697475	total: 17.1s	remaining: 25.2s
404:	learn: 0.2697080	total: 17.1s	remaining: 25.2s
405:	learn: 0.2696421	total: 17.2s	remaining: 25.1s
406:	learn: 0.2696046	total: 17.2s	remaining: 25.1s
407:	learn: 0.2695630	total: 17.3s	remaining: 25s
408:	learn: 0.2695297	total: 17.3s	remaining: 25s
409:	learn: 0.2695012	total: 17.3s	remaining: 24.9s
410:	learn: 0.2695000	total: 17.4s	remaining: 24.9s
411:	learn: 0.2694613	total: 17.4s	remaining: 24.8s
412:	learn: 0.2694030	total: 17.5s	remaining: 24.8s
413:	learn: 0.2693774	total: 17.5s	remaining: 24.7s
414:	learn: 0.2693566	total: 17.5s	remaining: 24.7s
415:	learn: 0.2692720	total: 17.6s	remaining: 24.7s
416:	learn: 0.2692468	total: 17.6s	remaining: 24.6s
417:	learn: 0.2692204	total: 17.7s	remaining: 24.6s
418:	learn: 0.2692117	total: 17.7s	remaining: 24.5s
419:	learn: 0.2692116	total: 17.8s	remaining: 24.5s
420:	learn: 0.2692116	total: 17.8s	remaining: 24.5s
421:	learn: 0.2692116	total: 17.8s	remaining: 24.4s
422:	learn: 0.2692076	total: 17.8s	remaining: 24.3s
423:	learn: 0.2691463	total: 17.9s	remaining: 24.3s
424:	learn: 0.2691216	total: 17.9s	remaining: 24.3s
425:	learn: 0.2690720	total: 18s	remaining: 24.2s
426:	learn: 0.2690170	total: 18s	remaining: 24.2s
427:	learn: 0.2689857	total: 18.1s	remaining: 24.2s
428:	learn: 0.2689102	total: 18.1s	remaining: 24.1s
429:	learn: 0.2689100	total: 18.1s	remaining: 24s
430:	learn: 0.2689099	total: 18.2s	remaining: 24s
431:	learn: 0.2688786	total: 18.2s	remaining: 23.9s
432:	learn: 0.2688425	total: 18.3s	remaining: 23.9s
433:	learn: 0.2687916	total: 18.3s	remaining: 23.9s
434:	learn: 0.2687889	total: 18.4s	remaining: 23.8s
435:	learn: 0.2687596	total: 18.4s	remaining: 23.8s
436:	learn: 0.2687126	total: 18.5s	remaining: 23.8s
437:	learn: 0.2686936	total: 18.5s	remaining: 23.7s
438:	learn: 0.2686880	total: 18.5s	remaining: 23.7s
439:	learn: 0.2686834	total: 18.6s	remaining: 23.6s
440:	learn: 0.2686834	total: 18.6s	remaining: 23.6s
441:	learn: 0.2686786	total: 18.6s	remaining: 23.5s
442:	learn: 0.2686287	total: 18.7s	remaining: 23.5s
443:	learn: 0.2685773	total: 18.7s	remaining: 23.5s
444:	learn: 0.2685653	total: 18.8s	remaining: 23.4s
445:	learn: 0.2685556	total: 18.8s	remaining: 23.4s
446:	learn: 0.2685286	total: 18.9s	remaining: 23.4s
447:	learn: 0.2685219	total: 18.9s	remaining: 23.3s
448:	learn: 0.2684978	total: 19s	remaining: 23.3s
449:	learn: 0.2683864	total: 19s	remaining: 23.2s
450:	learn: 0.2683778	total: 19.1s	remaining: 23.2s
451:	learn: 0.2683141	total: 19.1s	remaining: 23.1s
452:	learn: 0.2683051	total: 19.2s	remaining: 23.1s
453:	learn: 0.2682496	total: 19.2s	remaining: 23.1s
454:	learn: 0.2682496	total: 19.2s	remaining: 23s
455:	learn: 0.2682496	total: 19.3s	remaining: 23s
456:	learn: 0.2681889	total: 19.3s	remaining: 22.9s
457:	learn: 0.2681888	total: 19.3s	remaining: 22.9s
458:	learn: 0.2681888	total: 19.4s	remaining: 22.8s
459:	learn: 0.2681651	total: 19.4s	remaining: 22.8s
460:	learn: 0.2681651	total: 19.5s	remaining: 22.8s
461:	learn: 0.2681446	total: 19.5s	remaining: 22.7s
462:	learn: 0.2681031	total: 19.6s	remaining: 22.7s
463:	learn: 0.2680855	total: 19.6s	remaining: 22.6s
464:	learn: 0.2680566	total: 19.6s	remaining: 22.6s
465:	learn: 0.2680443	total: 19.7s	remaining: 22.5s
466:	learn: 0.2680298	total: 19.7s	remaining: 22.5s
467:	learn: 0.2680295	total: 19.8s	remaining: 22.5s
468:	learn: 0.2680124	total: 19.8s	remaining: 22.4s
469:	learn: 0.2679564	total: 19.8s	remaining: 22.4s
470:	learn: 0.2679563	total: 19.9s	remaining: 22.3s
471:	learn: 0.2679257	total: 19.9s	remaining: 22.3s
472:	learn: 0.2679034	total: 20s	remaining: 22.3s
473:	learn: 0.2678250	total: 20s	remaining: 22.2s
474:	learn: 0.2678120	total: 20.1s	remaining: 22.2s
475:	learn: 0.2677533	total: 20.1s	remaining: 22.1s
476:	learn: 0.2677300	total: 20.1s	remaining: 22.1s
477:	learn: 0.2677299	total: 20.2s	remaining: 22s
478:	learn: 0.2676803	total: 20.2s	remaining: 22s
479:	learn: 0.2676763	total: 20.3s	remaining: 21.9s
480:	learn: 0.2676733	total: 20.3s	remaining: 21.9s
481:	learn: 0.2676603	total: 20.3s	remaining: 21.9s
482:	learn: 0.2676340	total: 20.4s	remaining: 21.8s
483:	learn: 0.2676094	total: 20.4s	remaining: 21.8s
484:	learn: 0.2675684	total: 20.5s	remaining: 21.7s
485:	learn: 0.2675423	total: 20.5s	remaining: 21.7s
486:	learn: 0.2675213	total: 20.6s	remaining: 21.7s

487:	learn: 0.2674997	total: 20.6s	remaining: 21.6s
488:	learn: 0.2674848	total: 20.7s	remaining: 21.6s
489:	learn: 0.2674044	total: 20.7s	remaining: 21.6s
490:	learn: 0.2674014	total: 20.7s	remaining: 21.5s
491:	learn: 0.2673738	total: 20.8s	remaining: 21.5s
492:	learn: 0.2673691	total: 20.8s	remaining: 21.4s
493:	learn: 0.2673459	total: 20.9s	remaining: 21.4s
494:	learn: 0.2673277	total: 20.9s	remaining: 21.3s
495:	learn: 0.2673207	total: 21s	remaining: 21.3s
496:	learn: 0.2672769	total: 21s	remaining: 21.2s
497:	learn: 0.2672031	total: 21s	remaining: 21.2s
498:	learn: 0.2671334	total: 21.1s	remaining: 21.2s
499:	learn: 0.2670989	total: 21.1s	remaining: 21.1s
500:	learn: 0.2670678	total: 21.2s	remaining: 21.1s
501:	learn: 0.2670606	total: 21.2s	remaining: 21s
502:	learn: 0.2670606	total: 21.2s	remaining: 21s
503:	learn: 0.2670397	total: 21.3s	remaining: 20.9s
504:	learn: 0.2670353	total: 21.3s	remaining: 20.9s
505:	learn: 0.2670093	total: 21.3s	remaining: 20.8s
506:	learn: 0.2670031	total: 21.4s	remaining: 20.8s
507:	learn: 0.2670018	total: 21.4s	remaining: 20.7s
508:	learn: 0.2669284	total: 21.5s	remaining: 20.7s
509:	learn: 0.2668383	total: 21.5s	remaining: 20.7s
510:	learn: 0.2667968	total: 21.6s	remaining: 20.6s
511:	learn: 0.2667750	total: 21.6s	remaining: 20.6s
512:	learn: 0.2667113	total: 21.7s	remaining: 20.6s
513:	learn: 0.2666826	total: 21.7s	remaining: 20.5s
514:	learn: 0.2666158	total: 21.8s	remaining: 20.5s
515:	learn: 0.2666126	total: 21.8s	remaining: 20.5s
516:	learn: 0.2665643	total: 21.9s	remaining: 20.4s
517:	learn: 0.2665490	total: 21.9s	remaining: 20.4s
518:	learn: 0.2664908	total: 21.9s	remaining: 20.3s
519:	learn: 0.2664724	total: 22s	remaining: 20.3s
520:	learn: 0.2664662	total: 22s	remaining: 20.3s
521:	learn: 0.2664212	total: 22.1s	remaining: 20.2s
522:	learn: 0.2663497	total: 22.1s	remaining: 20.2s
523:	learn: 0.2663062	total: 22.1s	remaining: 20.1s
524:	learn: 0.2662813	total: 22.2s	remaining: 20.1s
525:	learn: 0.2662810	total: 22.2s	remaining: 20s
526:	learn: 0.2662371	total: 22.3s	remaining: 20s
527:	learn: 0.2662024	total: 22.3s	remaining: 19.9s
528:	learn: 0.2661994	total: 22.4s	remaining: 19.9s
529:	learn: 0.2661779	total: 22.4s	remaining: 19.9s
530:	learn: 0.2661359	total: 22.5s	remaining: 19.9s
531:	learn: 0.2660449	total: 22.5s	remaining: 19.8s
532:	learn: 0.2660449	total: 22.6s	remaining: 19.8s
533:	learn: 0.2660449	total: 22.6s	remaining: 19.7s
534:	learn: 0.2660039	total: 22.7s	remaining: 19.7s
535:	learn: 0.2660039	total: 22.7s	remaining: 19.6s
536:	learn: 0.2659743	total: 22.7s	remaining: 19.6s
537:	learn: 0.2659718	total: 22.8s	remaining: 19.6s
538:	learn: 0.2659718	total: 22.8s	remaining: 19.5s
539:	learn: 0.2659532	total: 22.8s	remaining: 19.5s
540:	learn: 0.2659200	total: 22.9s	remaining: 19.4s
541:	learn: 0.2659200	total: 22.9s	remaining: 19.4s
542:	learn: 0.2659155	total: 22.9s	remaining: 19.3s
543:	learn: 0.2658687	total: 23s	remaining: 19.3s
544:	learn: 0.2658313	total: 23.1s	remaining: 19.3s
545:	learn: 0.2658191	total: 23.1s	remaining: 19.2s
546:	learn: 0.2658191	total: 23.1s	remaining: 19.1s
547:	learn: 0.2657846	total: 23.1s	remaining: 19.1s
548:	learn: 0.2657473	total: 23.2s	remaining: 19.1s
549:	learn: 0.2657256	total: 23.2s	remaining: 19s
550:	learn: 0.2656902	total: 23.3s	remaining: 19s
551:	learn: 0.2656690	total: 23.3s	remaining: 18.9s
552:	learn: 0.2656382	total: 23.4s	remaining: 18.9s
553:	learn: 0.2656280	total: 23.4s	remaining: 18.8s
554:	learn: 0.2656223	total: 23.4s	remaining: 18.8s
555:	learn: 0.2655766	total: 23.5s	remaining: 18.7s
556:	learn: 0.2655573	total: 23.5s	remaining: 18.7s
557:	learn: 0.2655101	total: 23.6s	remaining: 18.7s
558:	learn: 0.2654625	total: 23.6s	remaining: 18.6s
559:	learn: 0.2654618	total: 23.6s	remaining: 18.6s
560:	learn: 0.2654294	total: 23.7s	remaining: 18.5s
561:	learn: 0.2654045	total: 23.7s	remaining: 18.5s
562:	learn: 0.2653715	total: 23.8s	remaining: 18.5s
563:	learn: 0.2653711	total: 23.9s	remaining: 18.4s
564:	learn: 0.2652913	total: 23.9s	remaining: 18.4s
565:	learn: 0.2652548	total: 24s	remaining: 18.4s
566:	learn: 0.2652499	total: 24s	remaining: 18.3s
567:	learn: 0.2652477	total: 24.1s	remaining: 18.3s
568:	learn: 0.2652340	total: 24.1s	remaining: 18.2s
569:	learn: 0.2651826	total: 24.1s	remaining: 18.2s
570:	learn: 0.2651794	total: 24.2s	remaining: 18.2s
571:	learn: 0.2651734	total: 24.2s	remaining: 18.1s
572:	learn: 0.2651669	total: 24.3s	remaining: 18.1s
573:	learn: 0.2651606	total: 24.3s	remaining: 18s
574:	learn: 0.2651358	total: 24.3s	remaining: 18s
575:	learn: 0.2650933	total: 24.4s	remaining: 17.9s
576:	learn: 0.2650538	total: 24.4s	remaining: 17.9s
577:	learn: 0.2650086	total: 24.5s	remaining: 17.9s
578:	learn: 0.2649825	total: 24.5s	remaining: 17.8s
579:	learn: 0.2649712	total: 24.6s	remaining: 17.8s
580:	learn: 0.2648793	total: 24.6s	remaining: 17.7s
581:	learn: 0.2648564	total: 24.7s	remaining: 17.7s
582:	learn: 0.2648387	total: 24.7s	remaining: 17.7s
583:	learn: 0.2648298	total: 24.7s	remaining: 17.6s
584:	learn: 0.2648298	total: 24.8s	remaining: 17.6s
585:	learn: 0.2648298	total: 24.8s	remaining: 17.5s
586:	learn: 0.2648082	total: 24.8s	remaining: 17.5s
587:	learn: 0.2647744	total: 24.9s	remaining: 17.4s
588:	learn: 0.2647541	total: 24.9s	remaining: 17.4s
589:	learn: 0.2647375	total: 25s	remaining: 17.4s
590:	learn: 0.2647351	total: 25s	remaining: 17.3s
591:	learn: 0.2646977	total: 25.1s	remaining: 17.3s
592:	learn: 0.2646977	total: 25.1s	remaining: 17.2s
593:	learn: 0.2646917	total: 25.2s	remaining: 17.2s
594:	learn: 0.2646916	total: 25.2s	remaining: 17.1s
595:	learn: 0.2646887	total: 25.2s	remaining: 17.1s
596:	learn: 0.2646797	total: 25.3s	remaining: 17.1s
597:	learn: 0.2646657	total: 25.3s	remaining: 17s
598:	learn: 0.2646488	total: 25.3s	remaining: 17s
599:	learn: 0.2646332	total: 25.4s	remaining: 16.9s
600:	learn: 0.2646317	total: 25.4s	remaining: 16.9s
601:	learn: 0.2646197	total: 25.5s	remaining: 16.9s
602:	learn: 0.2645979	total: 25.5s	remaining: 16.8s
603:	learn: 0.2645978	total: 25.6s	remaining: 16.8s
604:	learn: 0.2645960	total: 25.6s	remaining: 16.7s
605:	learn: 0.2645851	total: 25.6s	remaining: 16.7s
606:	learn: 0.2645786	total: 25.7s	remaining: 16.6s
607:	learn: 0.2645620	total: 25.7s	remaining: 16.6s
608:	learn: 0.2644720	total: 25.8s	remaining: 16.5s
609:	learn: 0.2644511	total: 25.8s	remaining: 16.5s
610:	learn: 0.2644454	total: 25.9s	remaining: 16.5s
611:	learn: 0.2644131	total: 25.9s	remaining: 16.4s
612:	learn: 0.2644074	total: 25.9s	remaining: 16.4s
613:	learn: 0.2643425	total: 26s	remaining: 16.3s
614:	learn: 0.2643330	total: 26s	remaining: 16.3s
615:	learn: 0.2642975	total: 26.1s	remaining: 16.3s
616:	learn: 0.2642361	total: 26.1s	remaining: 16.2s
617:	learn: 0.2641984	total: 26.2s	remaining: 16.2s
618:	learn: 0.2641775	total: 26.2s	remaining: 16.1s
619:	learn: 0.2641660	total: 26.3s	remaining: 16.1s
620:	learn: 0.2641611	total: 26.3s	remaining: 16s
621:	learn: 0.2641478	total: 26.4s	remaining: 16s
622:	learn: 0.2641287	total: 26.4s	remaining: 16s
623:	learn: 0.2641203	total: 26.4s	remaining: 15.9s
624:	learn: 0.2641148	total: 26.5s	remaining: 15.9s
625:	learn: 0.2641089	total: 26.5s	remaining: 15.8s
626:	learn: 0.2640813	total: 26.5s	remaining: 15.8s
627:	learn: 0.2640280	total: 26.6s	remaining: 15.8s
628:	learn: 0.2639047	total: 26.6s	remaining: 15.7s
629:	learn: 0.2638862	total: 26.7s	remaining: 15.7s
630:	learn: 0.2638833	total: 26.7s	remaining: 15.6s
631:	learn: 0.2638658	total: 26.8s	remaining: 15.6s
632:	learn: 0.2638485	total: 26.8s	remaining: 15.5s
633:	learn: 0.2637931	total: 26.9s	remaining: 15.5s
634:	learn: 0.2637482	total: 26.9s	remaining: 15.5s
635:	learn: 0.2637476	total: 26.9s	remaining: 15.4s
636:	learn: 0.2637325	total: 27s	remaining: 15.4s
637:	learn: 0.2637124	total: 27s	remaining: 15.3s
638:	learn: 0.2636955	total: 27s	remaining: 15.3s
639:	learn: 0.2636612	total: 27.1s	remaining: 15.2s
640:	learn: 0.2636466	total: 27.1s	remaining: 15.2s
641:	learn: 0.2635955	total: 27.2s	remaining: 15.2s
642:	learn: 0.2635527	total: 27.2s	remaining: 15.1s
643:	learn: 0.2635450	total: 27.3s	remaining: 15.1s
644:	learn: 0.2635308	total: 27.3s	remaining: 15s
645:	learn: 0.2634920	total: 27.4s	remaining: 15s
646:	learn: 0.2634484	total: 27.4s	remaining: 14.9s
647:	learn: 0.2634396	total: 27.4s	remaining: 14.9s
648:	learn: 0.2633920	total: 27.5s	remaining: 14.9s

649:	learn: 0.2633668	total: 27.5s	remaining: 14.8s
650:	learn: 0.2633618	total: 27.6s	remaining: 14.8s
651:	learn: 0.2633399	total: 27.6s	remaining: 14.7s
652:	learn: 0.2633041	total: 27.6s	remaining: 14.7s
653:	learn: 0.2632827	total: 27.7s	remaining: 14.6s
654:	learn: 0.2632329	total: 27.7s	remaining: 14.6s
655:	learn: 0.2632329	total: 27.7s	remaining: 14.5s
656:	learn: 0.2632228	total: 27.8s	remaining: 14.5s
657:	learn: 0.2632106	total: 27.8s	remaining: 14.5s
658:	learn: 0.2631929	total: 27.9s	remaining: 14.4s
659:	learn: 0.2631483	total: 27.9s	remaining: 14.4s
660:	learn: 0.2631229	total: 28s	remaining: 14.3s
661:	learn: 0.2630722	total: 28s	remaining: 14.3s
662:	learn: 0.2630695	total: 28.1s	remaining: 14.3s
663:	learn: 0.2630437	total: 28.1s	remaining: 14.2s
664:	learn: 0.2629904	total: 28.2s	remaining: 14.2s
665:	learn: 0.2629852	total: 28.2s	remaining: 14.1s
666:	learn: 0.2629821	total: 28.3s	remaining: 14.1s
667:	learn: 0.2629208	total: 28.3s	remaining: 14.1s
668:	learn: 0.2629045	total: 28.3s	remaining: 14s
669:	learn: 0.2628870	total: 28.4s	remaining: 14s
670:	learn: 0.2628700	total: 28.4s	remaining: 13.9s
671:	learn: 0.2628653	total: 28.5s	remaining: 13.9s
672:	learn: 0.2628388	total: 28.5s	remaining: 13.9s
673:	learn: 0.2628358	total: 28.6s	remaining: 13.8s
674:	learn: 0.2627949	total: 28.6s	remaining: 13.8s
675:	learn: 0.2627949	total: 28.7s	remaining: 13.7s
676:	learn: 0.2627741	total: 28.7s	remaining: 13.7s
677:	learn: 0.2627728	total: 28.8s	remaining: 13.7s
678:	learn: 0.2627719	total: 28.8s	remaining: 13.6s
679:	learn: 0.2627640	total: 28.9s	remaining: 13.6s
680:	learn: 0.2627640	total: 28.9s	remaining: 13.5s
681:	learn: 0.2627479	total: 29s	remaining: 13.5s
682:	learn: 0.2627351	total: 29s	remaining: 13.5s
683:	learn: 0.2627081	total: 29s	remaining: 13.4s
684:	learn: 0.2626967	total: 29.1s	remaining: 13.4s
685:	learn: 0.2626957	total: 29.1s	remaining: 13.3s
686:	learn: 0.2626841	total: 29.2s	remaining: 13.3s
687:	learn: 0.2626829	total: 29.2s	remaining: 13.3s
688:	learn: 0.2626232	total: 29.3s	remaining: 13.2s
689:	learn: 0.2626232	total: 29.3s	remaining: 13.2s
690:	learn: 0.2625969	total: 29.4s	remaining: 13.1s
691:	learn: 0.2625465	total: 29.4s	remaining: 13.1s
692:	learn: 0.2625089	total: 29.5s	remaining: 13s
693:	learn: 0.2625005	total: 29.5s	remaining: 13s
694:	learn: 0.2624998	total: 29.5s	remaining: 13s
695:	learn: 0.2624828	total: 29.6s	remaining: 12.9s
696:	learn: 0.2624643	total: 29.6s	remaining: 12.9s
697:	learn: 0.2624459	total: 29.7s	remaining: 12.9s
698:	learn: 0.2624172	total: 29.7s	remaining: 12.8s
699:	learn: 0.2624167	total: 29.8s	remaining: 12.8s
700:	learn: 0.2624023	total: 29.8s	remaining: 12.7s
701:	learn: 0.2623979	total: 29.9s	remaining: 12.7s
702:	learn: 0.2623836	total: 29.9s	remaining: 12.6s
703:	learn: 0.2623799	total: 29.9s	remaining: 12.6s
704:	learn: 0.2623752	total: 30s	remaining: 12.6s
705:	learn: 0.2623744	total: 30s	remaining: 12.5s
706:	learn: 0.2623744	total: 30.1s	remaining: 12.5s
707:	learn: 0.2623710	total: 30.1s	remaining: 12.4s
708:	learn: 0.2623286	total: 30.2s	remaining: 12.4s
709:	learn: 0.2623215	total: 30.2s	remaining: 12.3s
710:	learn: 0.2623133	total: 30.3s	remaining: 12.3s
711:	learn: 0.2622888	total: 30.3s	remaining: 12.3s
712:	learn: 0.2622868	total: 30.3s	remaining: 12.2s
713:	learn: 0.2622663	total: 30.3s	remaining: 12.2s
714:	learn: 0.2622396	total: 30.4s	remaining: 12.1s
715:	learn: 0.2622391	total: 30.4s	remaining: 12.1s
716:	learn: 0.2622069	total: 30.5s	remaining: 12s
717:	learn: 0.2622040	total: 30.6s	remaining: 12s
718:	learn: 0.2621835	total: 30.6s	remaining: 12s
719:	learn: 0.2621528	total: 30.6s	remaining: 11.9s
720:	learn: 0.2621528	total: 30.7s	remaining: 11.9s
721:	learn: 0.2621341	total: 30.7s	remaining: 11.8s
722:	learn: 0.2621080	total: 30.8s	remaining: 11.8s
723:	learn: 0.2620816	total: 30.8s	remaining: 11.7s
724:	learn: 0.2620727	total: 30.8s	remaining: 11.7s
725:	learn: 0.2620622	total: 30.9s	remaining: 11.7s
726:	learn: 0.2620552	total: 30.9s	remaining: 11.6s
727:	learn: 0.2620527	total: 31s	remaining: 11.6s
728:	learn: 0.2620397	total: 31s	remaining: 11.5s
729:	learn: 0.2620375	total: 31.1s	remaining: 11.5s
730:	learn: 0.2620050	total: 31.1s	remaining: 11.5s
731:	learn: 0.2619550	total: 31.2s	remaining: 11.4s
732:	learn: 0.2619316	total: 31.2s	remaining: 11.4s
733:	learn: 0.2618514	total: 31.3s	remaining: 11.3s
734:	learn: 0.2618383	total: 31.3s	remaining: 11.3s
735:	learn: 0.2618130	total: 31.4s	remaining: 11.2s
736:	learn: 0.2617939	total: 31.4s	remaining: 11.2s
737:	learn: 0.2617722	total: 31.5s	remaining: 11.2s
738:	learn: 0.2617478	total: 31.5s	remaining: 11.1s
739:	learn: 0.2616836	total: 31.6s	remaining: 11.1s
740:	learn: 0.2616757	total: 31.6s	remaining: 11s
741:	learn: 0.2616677	total: 31.6s	remaining: 11s
742:	learn: 0.2616600	total: 31.7s	remaining: 11s
743:	learn: 0.2616478	total: 31.7s	remaining: 10.9s
744:	learn: 0.2616379	total: 31.8s	remaining: 10.9s
745:	learn: 0.2616225	total: 31.8s	remaining: 10.8s
746:	learn: 0.2616094	total: 31.9s	remaining: 10.8s
747:	learn: 0.2616094	total: 31.9s	remaining: 10.7s
748:	learn: 0.2616050	total: 31.9s	remaining: 10.7s
749:	learn: 0.2616035	total: 32s	remaining: 10.7s
750:	learn: 0.2615345	total: 32s	remaining: 10.6s
751:	learn: 0.2615139	total: 32s	remaining: 10.6s
752:	learn: 0.2615113	total: 32.1s	remaining: 10.5s
753:	learn: 0.2614907	total: 32.1s	remaining: 10.5s
754:	learn: 0.2614299	total: 32.2s	remaining: 10.4s
755:	learn: 0.2614220	total: 32.3s	remaining: 10.4s
756:	learn: 0.2613782	total: 32.3s	remaining: 10.4s
757:	learn: 0.2613774	total: 32.4s	remaining: 10.3s
758:	learn: 0.2613421	total: 32.4s	remaining: 10.3s
759:	learn: 0.2613163	total: 32.5s	remaining: 10.3s
760:	learn: 0.2612605	total: 32.5s	remaining: 10.2s
761:	learn: 0.2612513	total: 32.5s	remaining: 10.2s
762:	learn: 0.2612160	total: 32.6s	remaining: 10.1s
763:	learn: 0.2611695	total: 32.7s	remaining: 10.1s
764:	learn: 0.2611412	total: 32.7s	remaining: 10s
765:	learn: 0.2610916	total: 32.7s	remaining: 10s
766:	learn: 0.2610525	total: 32.8s	remaining: 9.95s
767:	learn: 0.2610516	total: 32.8s	remaining: 9.91s
768:	learn: 0.2610057	total: 32.9s	remaining: 9.88s
769:	learn: 0.2609725	total: 32.9s	remaining: 9.83s
770:	learn: 0.2609470	total: 33s	remaining: 9.79s
771:	learn: 0.2609389	total: 33s	remaining: 9.74s
772:	learn: 0.2609085	total: 33.1s	remaining: 9.71s
773:	learn: 0.2608789	total: 33.1s	remaining: 9.66s
774:	learn: 0.2608647	total: 33.1s	remaining: 9.62s
775:	learn: 0.2608539	total: 33.2s	remaining: 9.57s
776:	learn: 0.2608404	total: 33.2s	remaining: 9.54s
777:	learn: 0.2608259	total: 33.3s	remaining: 9.49s
778:	learn: 0.2608186	total: 33.3s	remaining: 9.45s
779:	learn: 0.2608162	total: 33.3s	remaining: 9.4s
780:	learn: 0.2608127	total: 33.4s	remaining: 9.36s
781:	learn: 0.2607994	total: 33.4s	remaining: 9.32s
782:	learn: 0.2607955	total: 33.5s	remaining: 9.28s
783:	learn: 0.2607760	total: 33.5s	remaining: 9.23s
784:	learn: 0.2607668	total: 33.6s	remaining: 9.19s
785:	learn: 0.2607446	total: 33.6s	remaining: 9.15s
786:	learn: 0.2607236	total: 33.7s	remaining: 9.11s
787:	learn: 0.2607036	total: 33.7s	remaining: 9.07s
788:	learn: 0.2606985	total: 33.7s	remaining: 9.02s
789:	learn: 0.2606584	total: 33.8s	remaining: 8.98s
790:	learn: 0.2606576	total: 33.8s	remaining: 8.94s
791:	learn: 0.2606150	total: 33.9s	remaining: 8.9s
792:	learn: 0.2605929	total: 33.9s	remaining: 8.85s
793:	learn: 0.2605462	total: 34s	remaining: 8.81s
794:	learn: 0.2605443	total: 34s	remaining: 8.77s
795:	learn: 0.2605163	total: 34.1s	remaining: 8.73s
796:	learn: 0.2605056	total: 34.1s	remaining: 8.69s
797:	learn: 0.2604986	total: 34.2s	remaining: 8.64s
798:	learn: 0.2604953	total: 34.2s	remaining: 8.61s
799:	learn: 0.2604604	total: 34.2s	remaining: 8.56s
800:	learn: 0.2604371	total: 34.3s	remaining: 8.52s
801:	learn: 0.2604339	total: 34.3s	remaining: 8.47s
802:	learn: 0.2604190	total: 34.4s	remaining: 8.43s
803:	learn: 0.2604104	total: 34.4s	remaining: 8.39s
804:	learn: 0.2603845	total: 34.5s	remaining: 8.35s
805:	learn: 0.2603835	total: 34.5s	remaining: 8.3s
806:	learn: 0.2603792	total: 34.5s	remaining: 8.26s
807:	learn: 0.2603173	total: 34.6s	remaining: 8.21s
808:	learn: 0.2603061	total: 34.6s	remaining: 8.18s
809:	learn: 0.2602942	total: 34.7s	remaining: 8.13s

810:	learn: 0.2602813	total: 34.7s	remaining: 8.09s
811:	learn: 0.2602579	total: 34.8s	remaining: 8.05s
812:	learn: 0.2602318	total: 34.8s	remaining: 8.01s
813:	learn: 0.2602297	total: 34.9s	remaining: 7.96s
814:	learn: 0.2601618	total: 34.9s	remaining: 7.92s
815:	learn: 0.2601566	total: 35s	remaining: 7.88s
816:	learn: 0.2601306	total: 35s	remaining: 7.84s
817:	learn: 0.2601222	total: 35s	remaining: 7.79s
818:	learn: 0.2601162	total: 35.1s	remaining: 7.75s
819:	learn: 0.2601156	total: 35.1s	remaining: 7.71s
820:	learn: 0.2601033	total: 35.2s	remaining: 7.66s
821:	learn: 0.2601019	total: 35.2s	remaining: 7.63s
822:	learn: 0.2600957	total: 35.2s	remaining: 7.58s
823:	learn: 0.2600899	total: 35.3s	remaining: 7.54s
824:	learn: 0.2600875	total: 35.3s	remaining: 7.49s
825:	learn: 0.2600334	total: 35.4s	remaining: 7.45s
826:	learn: 0.2600271	total: 35.4s	remaining: 7.41s
827:	learn: 0.2600264	total: 35.5s	remaining: 7.37s
828:	learn: 0.2600238	total: 35.5s	remaining: 7.32s
829:	learn: 0.2600126	total: 35.6s	remaining: 7.29s
830:	learn: 0.2600123	total: 35.6s	remaining: 7.25s
831:	learn: 0.2600045	total: 35.7s	remaining: 7.2s
832:	learn: 0.2600031	total: 35.7s	remaining: 7.16s
833:	learn: 0.2599957	total: 35.7s	remaining: 7.12s
834:	learn: 0.2599950	total: 35.8s	remaining: 7.07s
835:	learn: 0.2599832	total: 35.8s	remaining: 7.03s
836:	learn: 0.2599216	total: 35.9s	remaining: 6.99s
837:	learn: 0.2599178	total: 35.9s	remaining: 6.95s
838:	learn: 0.2599129	total: 36s	remaining: 6.9s
839:	learn: 0.2599029	total: 36s	remaining: 6.86s
840:	learn: 0.2598895	total: 36.1s	remaining: 6.82s
841:	learn: 0.2598711	total: 36.1s	remaining: 6.78s
842:	learn: 0.2598662	total: 36.2s	remaining: 6.73s
843:	learn: 0.2598596	total: 36.2s	remaining: 6.7s
844:	learn: 0.2598567	total: 36.3s	remaining: 6.65s
845:	learn: 0.2598554	total: 36.3s	remaining: 6.61s
846:	learn: 0.2598381	total: 36.3s	remaining: 6.57s
847:	learn: 0.2598370	total: 36.4s	remaining: 6.52s
848:	learn: 0.2598361	total: 36.4s	remaining: 6.48s
849:	learn: 0.2598345	total: 36.5s	remaining: 6.44s
850:	learn: 0.2598005	total: 36.5s	remaining: 6.39s
851:	learn: 0.2597835	total: 36.6s	remaining: 6.35s
852:	learn: 0.2597664	total: 36.6s	remaining: 6.31s
853:	learn: 0.2597633	total: 36.7s	remaining: 6.27s
854:	learn: 0.2597604	total: 36.7s	remaining: 6.22s
855:	learn: 0.2597566	total: 36.7s	remaining: 6.18s
856:	learn: 0.2597536	total: 36.8s	remaining: 6.13s
857:	learn: 0.2597534	total: 36.8s	remaining: 6.09s
858:	learn: 0.2597446	total: 36.8s	remaining: 6.05s
859:	learn: 0.2597426	total: 36.9s	remaining: 6.01s
860:	learn: 0.2597418	total: 37s	remaining: 5.97s
861:	learn: 0.2596685	total: 37s	remaining: 5.92s
862:	learn: 0.2596681	total: 37s	remaining: 5.88s
863:	learn: 0.2596675	total: 37.1s	remaining: 5.84s
864:	learn: 0.2596627	total: 37.1s	remaining: 5.8s
865:	learn: 0.2596293	total: 37.2s	remaining: 5.75s
866:	learn: 0.2596247	total: 37.2s	remaining: 5.71s
867:	learn: 0.2596091	total: 37.3s	remaining: 5.67s
868:	learn: 0.2596028	total: 37.3s	remaining: 5.63s
869:	learn: 0.2596028	total: 37.3s	remaining: 5.58s
870:	learn: 0.2596015	total: 37.4s	remaining: 5.54s
871:	learn: 0.2596007	total: 37.4s	remaining: 5.49s
872:	learn: 0.2595919	total: 37.5s	remaining: 5.45s
873:	learn: 0.2595822	total: 37.5s	remaining: 5.41s
874:	learn: 0.2595754	total: 37.6s	remaining: 5.37s
875:	learn: 0.2595735	total: 37.6s	remaining: 5.32s
876:	learn: 0.2595542	total: 37.7s	remaining: 5.28s
877:	learn: 0.2595537	total: 37.7s	remaining: 5.24s
878:	learn: 0.2595527	total: 37.7s	remaining: 5.2s
879:	learn: 0.2595476	total: 37.8s	remaining: 5.15s
880:	learn: 0.2595428	total: 37.8s	remaining: 5.11s
881:	learn: 0.2595388	total: 37.9s	remaining: 5.06s
882:	learn: 0.2595320	total: 37.9s	remaining: 5.02s
883:	learn: 0.2595231	total: 37.9s	remaining: 4.98s
884:	learn: 0.2595225	total: 38s	remaining: 4.94s
885:	learn: 0.2594963	total: 38s	remaining: 4.89s
886:	learn: 0.2594957	total: 38.1s	remaining: 4.85s
887:	learn: 0.2594931	total: 38.1s	remaining: 4.8s
888:	learn: 0.2594910	total: 38.2s	remaining: 4.76s
889:	learn: 0.2594822	total: 38.2s	remaining: 4.72s
890:	learn: 0.2594424	total: 38.2s	remaining: 4.68s
891:	learn: 0.2594387	total: 38.3s	remaining: 4.63s
892:	learn: 0.2594337	total: 38.3s	remaining: 4.59s
893:	learn: 0.2594254	total: 38.4s	remaining: 4.55s
894:	learn: 0.2594238	total: 38.4s	remaining: 4.5s
895:	learn: 0.2594098	total: 38.4s	remaining: 4.46s
896:	learn: 0.2594071	total: 38.5s	remaining: 4.42s
897:	learn: 0.2594045	total: 38.5s	remaining: 4.38s
898:	learn: 0.2593847	total: 38.6s	remaining: 4.33s
899:	learn: 0.2593742	total: 38.6s	remaining: 4.29s
900:	learn: 0.2593614	total: 38.7s	remaining: 4.25s
901:	learn: 0.2593552	total: 38.7s	remaining: 4.2s
902:	learn: 0.2593345	total: 38.8s	remaining: 4.16s
903:	learn: 0.2593336	total: 38.8s	remaining: 4.12s
904:	learn: 0.2593231	total: 38.8s	remaining: 4.08s
905:	learn: 0.2593229	total: 38.9s	remaining: 4.03s
906:	learn: 0.2593102	total: 38.9s	remaining: 3.99s
907:	learn: 0.2592553	total: 38.9s	remaining: 3.94s
908:	learn: 0.2592545	total: 39s	remaining: 3.9s
909:	learn: 0.2592543	total: 39.1s	remaining: 3.86s
910:	learn: 0.2592531	total: 39.1s	remaining: 3.82s
911:	learn: 0.2592521	total: 39.1s	remaining: 3.77s
912:	learn: 0.2592004	total: 39.2s	remaining: 3.73s
913:	learn: 0.2591669	total: 39.2s	remaining: 3.69s
914:	learn: 0.2591610	total: 39.3s	remaining: 3.65s
915:	learn: 0.2590958	total: 39.3s	remaining: 3.6s
916:	learn: 0.2590940	total: 39.3s	remaining: 3.56s
917:	learn: 0.2590876	total: 39.4s	remaining: 3.52s
918:	learn: 0.2590837	total: 39.4s	remaining: 3.47s
919:	learn: 0.2590796	total: 39.4s	remaining: 3.43s
920:	learn: 0.2590431	total: 39.5s	remaining: 3.39s
921:	learn: 0.2590332	total: 39.6s	remaining: 3.35s
922:	learn: 0.2590029	total: 39.6s	remaining: 3.3s
923:	learn: 0.2589757	total: 39.6s	remaining: 3.26s
924:	learn: 0.2589713	total: 39.7s	remaining: 3.22s
925:	learn: 0.2589680	total: 39.7s	remaining: 3.18s
926:	learn: 0.2589284	total: 39.8s	remaining: 3.13s
927:	learn: 0.2589275	total: 39.8s	remaining: 3.09s
928:	learn: 0.2589200	total: 39.9s	remaining: 3.04s
929:	learn: 0.2588810	total: 39.9s	remaining: 3s
930:	learn: 0.2588626	total: 39.9s	remaining: 2.96s
931:	learn: 0.2588626	total: 40s	remaining: 2.92s
932:	learn: 0.2588431	total: 40s	remaining: 2.87s
933:	learn: 0.2588421	total: 40.1s	remaining: 2.83s
934:	learn: 0.2588398	total: 40.1s	remaining: 2.79s
935:	learn: 0.2588394	total: 40.2s	remaining: 2.75s
936:	learn: 0.2588367	total: 40.2s	remaining: 2.71s
937:	learn: 0.2588315	total: 40.3s	remaining: 2.66s
938:	learn: 0.2588112	total: 40.3s	remaining: 2.62s
939:	learn: 0.2588100	total: 40.4s	remaining: 2.58s
940:	learn: 0.2588092	total: 40.4s	remaining: 2.53s
941:	learn: 0.2588079	total: 40.5s	remaining: 2.49s
942:	learn: 0.2588037	total: 40.5s	remaining: 2.45s
943:	learn: 0.2587999	total: 40.6s	remaining: 2.41s
944:	learn: 0.2587991	total: 40.6s	remaining: 2.36s
945:	learn: 0.2587969	total: 40.6s	remaining: 2.32s
946:	learn: 0.2587911	total: 40.7s	remaining: 2.28s
947:	learn: 0.2587729	total: 40.8s	remaining: 2.24s
948:	learn: 0.2587724	total: 40.8s	remaining: 2.19s
949:	learn: 0.2587599	total: 40.8s	remaining: 2.15s
950:	learn: 0.2587543	total: 40.9s	remaining: 2.11s
951:	learn: 0.2587538	total: 40.9s	remaining: 2.06s
952:	learn: 0.2587277	total: 41s	remaining: 2.02s
953:	learn: 0.2587276	total: 41s	remaining: 1.98s
954:	learn: 0.2587250	total: 41.1s	remaining: 1.94s
955:	learn: 0.2587221	total: 41.1s	remaining: 1.89s
956:	learn: 0.2587219	total: 41.2s	remaining: 1.85s
957:	learn: 0.2587162	total: 41.2s	remaining: 1.8s
958:	learn: 0.2587100	total: 41.3s	remaining: 1.76s
959:	learn: 0.2586379	total: 41.3s	remaining: 1.72s
960:	learn: 0.2586355	total: 41.3s	remaining: 1.68s
961:	learn: 0.2585952	total: 41.4s	remaining: 1.63s
962:	learn: 0.2585945	total: 41.5s	remaining: 1.59s
963:	learn: 0.2585939	total: 41.5s	remaining: 1.55s
964:	learn: 0.2585870	total: 41.5s	remaining: 1.51s
965:	learn: 0.2585857	total: 41.6s	remaining: 1.46s
966:	learn: 0.2585856	total: 41.6s	remaining: 1.42s
967:	learn: 0.2585606	total: 41.7s	remaining: 1.38s
968:	learn: 0.2585479	total: 41.7s	remaining: 1.33s
969:	learn: 0.2584985	total: 41.7s	remaining: 1.29s
970:	learn: 0.2584919	total: 41.8s	remaining: 1.25s
971:	learn: 0.2584886	total: 41.8s	remaining: 1.21s
972:	learn: 0.2584418	total: 41.9s	remaining: 1.16s
973:	learn: 0.2584138	total: 41.9s	remaining: 1.12s

974:	learn: 0.2584135	total: 42s	remaining: 1.08s
975:	learn: 0.2583908	total: 42s	remaining: 1.03s
976:	learn: 0.2583881	total: 42.1s	remaining: 990ms
977:	learn: 0.2583879	total: 42.1s	remaining: 947ms
978:	learn: 0.2583867	total: 42.1s	remaining: 904ms
979:	learn: 0.2583796	total: 42.2s	remaining: 860ms
980:	learn: 0.2583636	total: 42.2s	remaining: 818ms
981:	learn: 0.2583635	total: 42.2s	remaining: 774ms
982:	learn: 0.2583634	total: 42.3s	remaining: 731ms
983:	learn: 0.2583431	total: 42.3s	remaining: 688ms
984:	learn: 0.2583427	total: 42.4s	remaining: 645ms
985:	learn: 0.2583056	total: 42.4s	remaining: 602ms
986:	learn: 0.2582866	total: 42.5s	remaining: 559ms
987:	learn: 0.2582860	total: 42.5s	remaining: 516ms
988:	learn: 0.2582860	total: 42.5s	remaining: 473ms
989:	learn: 0.2582576	total: 42.6s	remaining: 430ms
990:	learn: 0.2582567	total: 42.6s	remaining: 387ms
991:	learn: 0.2582394	total: 42.6s	remaining: 344ms
992:	learn: 0.2582086	total: 42.7s	remaining: 301ms
993:	learn: 0.2582004	total: 42.7s	remaining: 258ms
994:	learn: 0.2581804	total: 42.8s	remaining: 215ms
995:	learn: 0.2581781	total: 42.8s	remaining: 172ms
996:	learn: 0.2581757	total: 42.9s	remaining: 129ms
997:	learn: 0.2581750	total: 42.9s	remaining: 86ms
998:	learn: 0.2581704	total: 43s	remaining: 43ms
999:	learn: 0.2581685	total: 43s	remaining: 0us
0.8828316953316954
0.8762475049900199

In [55]:
data1 = pd.read_csv("test.csv")

In [56]:
data1.isnull().any()

age               False
workclass          True
final_weight      False
education         False
Learning years    False
marital-status    False
occupation         True
relationship      False
sex               False
capital-gain      False
capital-loss      False
Workrate          False
native-country     True
Id                False
dtype: bool

In [57]:
from sklearn.preprocessing import LabelEncoder,MinMaxScaler,OneHotEncoder
labelencoder = LabelEncoder()
# data['workclass']=data['workclass'].astype('category')
data1['workclass'] = labelencoder.fit_transform(data1['workclass'].astype(str))
data1['education'] = labelencoder.fit_transform(data1['education'])
# data1['marital-status'] = labelencoder.fit_transform(data1['marital-status'])
# data['occupation']=data['occupation'].astype('category')
data1['occupation'] = labelencoder.fit_transform(data1['occupation'].astype(str))
# data1['relationship'] = labelencoder.fit_transform(data1['relationship'])
# data1['sex'] = labelencoder.fit_transform(data1['sex'])
data1['native-country'] = labelencoder.fit_transform(data1['native-country'].astype(str))
data1.head()

,age,workclass,final_weight,education,Learning years,marital-status,occupation,relationship,sex,capital-gain,capital-loss,Workrate,native-country,Id
0,49,3,182313,11,9,Divorced,5,Not-in-family,Male,0,0,40,37,32562
1,66,5,183249,9,13,Married-civ-spouse,9,Husband,Male,0,0,20,37,32563
2,26,3,264300,7,12,Never-married,0,Own-child,Female,0,0,40,37,32564
3,43,1,201764,14,15,Never-married,9,Not-in-family,Male,0,0,40,37,32565
4,63,0,90393,15,10,Married-civ-spouse,0,Husband,Male,0,0,48,37,32566

In [58]:
data1.describe()

,age,workclass,final_weight,education,Learning years,occupation,capital-gain,capital-loss,Workrate,native-country,Id
count,16281.000000,16281.000000,1.628100e+04,16281.000000,16281.000000,16281.000000,16281.000000,16281.000000,16281.000000,16281.000000,16281.000000
mean,38.767459,3.405872,1.894357e+05,10.268841,10.072907,6.477612,1081.905104,87.899269,40.392236,35.546342,40702.000000
std,13.849187,1.605006,1.057149e+05,3.882980,2.567545,4.331064,7583.935968,403.105286,12.479332,5.861429,4700.064202
min,17.000000,0.000000,1.349200e+04,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,32562.000000
25%,28.000000,3.000000,1.167360e+05,9.000000,9.000000,3.000000,0.000000,0.000000,40.000000,37.000000,36632.000000
50%,37.000000,3.000000,1.778310e+05,11.000000,10.000000,7.000000,0.000000,0.000000,40.000000,37.000000,40702.000000
75%,48.000000,3.000000,2.383840e+05,12.000000,12.000000,11.000000,0.000000,0.000000,45.000000,37.000000,44772.000000
max,90.000000,8.000000,1.490400e+06,15.000000,16.000000,14.000000,99999.000000,3770.000000,99.000000,40.000000,48842.000000

In [59]:
data1["occupation"].fillna("6.337141", inplace = True) 
data1["native-country"].fillna("30.036361", inplace = True) 
data1["workclass"].fillna("3.873534", inplace = True)

In [60]:
# for index, row in data1.iterrows():
#     data1.at[index,'net']=data1.loc[index,'capital-gain']+data1.loc[index,'capital-loss']

In [61]:
data1.drop(['marital-status'], axis=1, inplace=True)
# data1.drop(['capital-gain'], axis=1, inplace=True)
data1.drop(['education'], axis=1, inplace=True)
# data1.drop(['capital-loss'], axis=1, inplace=True)
# data1.drop(['sex'], axis=1, inplace=True)
# data1.drop(['native-country'], axis=1, inplace=True)

In [62]:
# cleanup_nums = {"native-country":{"United-States": 1}}

In [63]:
# data1.replace(cleanup_nums, inplace=True)

In [64]:
cleanup_nums = {"sex":{"Female": 0,"Male": 1}}

In [65]:
data1.replace(cleanup_nums, inplace=True)

In [66]:
# cleanup_nums = {"native-country":{"Mexico": 0,"South": 2,"Dominican-Republic":39,"Philippines":3,"Taiwan":4,"Poland":5,"Cambodia":6,"Italy":7
#                                  ,"Cuba":8,"Jamaica":9,"Vietnam":10,"Canada":11,"El-Salvador":11,"Iran":12,"China":13,"Hong":14,"Haiti":15
#                                  ,"India":16,"Trinadad&Tobago":17,"Japan":18,"England":19,"Columbia":20,"Thailand":21,"Ireland":22
#                                  ,"Germany":23,"France":24,"Guatemala":25,"Honduras":26,"Greece":27,"Nicaragua":28,
#                                  "Puerto-Rico":29,"Peru":30,"Portugal":31,"Yugoslavia":32,"Hungary":33,"Laos":34,"Ecuador":35
#                                  ,"Scotland":36,"Outlying-US(Guam-USVI-etc)":37,"Holand-Netherlands":38}}

In [67]:
# data1.replace(cleanup_nums, inplace=True)

In [68]:
cleanup_nums = {"relationship":{"Husband": 1,"Other-relative": 0,"Wife":1,"Not-in-family":0,"Own-child":0,"Unmarried":0}}

In [69]:
data1.replace(cleanup_nums, inplace=True)

In [70]:
cleanup_nums = {"marital-status":{"Married-civ-spouse": 1,"Divorced": 0,"Never-married":0,"Separated":0,
                                  "Widowed":0,"Married-spouse-absent":0,"Married-AF-spouse":1}}

In [71]:
data1.replace(cleanup_nums, inplace=True)

In [72]:
# cleanup_nums = {"workclass":{"Private": 1,"State-gov": 0,"Local-gov":2,"Federal-gov":3,"Self-emp-not-inc":4,
#                              "Self-emp-inc":5,"Without-pay":6,"Never-worked":7}}

In [73]:
# data1.replace(cleanup_nums, inplace=True)

In [74]:
# cleanup_nums = {"occupation":{"Tech-support":0,
# "Transport-moving":1,
# "Sales":2,
# "Adm-clerical":3,
# "Craft-repair":4,
# "Exec-managerial":5,
# "Handlers-cleaners":6,
# "Farming-fishing":7,
# "Sales":8,
# "Machine-op-inspct":9,
# "Prof-specialty":10,
# "Other-service":11,"Protective-serv":12,"Armed-Forces":13,"Priv-house-serv":14
# }}

In [75]:
# data1.replace(cleanup_nums, inplace=True)

In [76]:
# cleanup_nums = {"education":{"Assoc-acdm":0,
# "HS-grad":1,
# "5th-6th":2,
# "9th":3,
# "Bachelors":4,
# "Masters":5,
# "Assoc-voc":6,
# "11th":7,
# "Prof-school":8,
# "Preschool":9,
# "Prof-specialty":10,
# "10th":11,"7th-8th":12,"12th":13,"Some-college":14,"Doctorate":15,"1st-4th":16
# }}

In [77]:
data1.head()

,age,workclass,final_weight,Learning years,occupation,relationship,sex,capital-gain,capital-loss,Workrate,native-country,Id
0,49,3,182313,9,5,0,1,0,0,40,37,32562
1,66,5,183249,13,9,1,1,0,0,20,37,32563
2,26,3,264300,12,0,0,0,0,0,40,37,32564
3,43,1,201764,15,9,0,1,0,0,40,37,32565
4,63,0,90393,10,0,1,1,0,0,48,37,32566

In [78]:
data1.shape

(16281, 12)

In [79]:
Id = data1["Id"]

In [80]:
# data1= data1.drop(["relationship"],axis=1)
X1=data1.drop(["Id"],axis=1)

In [81]:
scaler=StandardScaler()
X1 = scaler.fit_transform(X1)
X1.shape

(16281, 11)

In [82]:
X.shape

(32561, 11)

In [83]:
prediction_test=ct.predict(X1)

In [84]:
prediction_test=prediction_test.astype(int)

In [85]:
my_solution=pd.DataFrame(prediction_test,Id,columns=["Prediction"])
print(my_solution.shape)

(16281, 1)

In [86]:
my_solution.to_csv("prediction123.csv",index_label=["Id"])